# https://sugang.khu.ac.kr/resources/data/data_2022.js 의 데이터 그대로입니다.
# js => python으로 변환했을 뿐입니다.

daehak_202210 = {"rows":[
{"id":1,"enm":"College of Humanities","or_seq":"10","up":"A10081","nm":"문과대학","cd":"A01008","gb":"H"},
{"id":2,"enm":"College of Law","or_seq":"15","up":"A10081","nm":"법과대학","cd":"A00400","gb":"H"},
{"id":3,"enm":"College of Politics & Economics","or_seq":"20","up":"A10081","nm":"정경대학","cd":"A00422","gb":"H"},
{"id":4,"enm":"College of Business Administration","or_seq":"30","up":"A10081","nm":"경영대학","cd":"A01024","gb":"H"},
{"id":5,"enm":"College of Hotel and Tourism Management","or_seq":"40","up":"A10081","nm":"호텔관광대학","cd":"A00681","gb":"H"},
{"id":6,"enm":"College of Sciences","or_seq":"50","up":"A10081","nm":"이과대학","cd":"A01043","gb":"H"},
{"id":7,"enm":"College of Human Ecology","or_seq":"60","up":"A10081","nm":"생활과학대학","cd":"A00556","gb":"H"},
{"id":8,"enm":"College of Medicine","or_seq":"70","up":"A10081","nm":"의과대학","cd":"A00585","gb":"H"},
{"id":9,"enm":"College of Korean Medicine","or_seq":"75","up":"A10081","nm":"한의과대학","cd":"A00613","gb":"H"},
{"id":10,"enm":"College of Dentistry","or_seq":"80","up":"A10081","nm":"치과대학","cd":"A00622","gb":"H"},
{"id":11,"enm":"College of Pharmacy","or_seq":"85","up":"A10081","nm":"약학대학","cd":"A00632","gb":"H"},
{"id":12,"enm":"College of Nursing Science","or_seq":"90","up":"A10081","nm":"간호과학대학","cd":"A01074","gb":"H"},
{"id":13,"enm":"College of Music","or_seq":"100","up":"A10081","nm":"음악대학","cd":"A00645","gb":"H"},
{"id":14,"enm":"College of Fine Arts","or_seq":"110","up":"A10081","nm":"미술대학","cd":"A01085","gb":"H"},
{"id":15,"enm":"School of Dance","or_seq":"130","up":"A10081","nm":"무용학부","cd":"A01101","gb":"H"},
{"id":16,"enm":"Department of Global Eminence","or_seq":"150","up":"A10081","nm":"자율전공학부","cd":"A10466","gb":"H"},
{"id":17,"enm":"College of Engineering","or_seq":"500","up":"A10081","nm":"공과대학","cd":"A04754","gb":"H"},
{"id":18,"enm":"College of Electronics and Information","or_seq":"510","up":"A10081","nm":"전자정보대학","cd":"A05091","gb":"H"},
{"id":19,"enm":"College of Software","or_seq":"520","up":"A10081","nm":"소프트웨어융합대학","cd":"A07340","gb":"H"},
{"id":20,"enm":"College of Applied Science","or_seq":"530","up":"A10081","nm":"응용과학대학","cd":"A05346","gb":"H"},
{"id":21,"enm":"College of Life Sciences","or_seq":"540","up":"A10081","nm":"생명과학대학","cd":"A05165","gb":"H"},
{"id":22,"enm":"College of International Studies","or_seq":"550","up":"A10081","nm":"국제대학","cd":"A05366","gb":"H"},
{"id":23,"enm":"College of Foreign Language & Literature","or_seq":"560","up":"A10081","nm":"외국어대학","cd":"A04620","gb":"H"},
{"id":24,"enm":"College of Art & Design","or_seq":"570","up":"A10081","nm":"예술·디자인대학","cd":"A05240","gb":"H"},
{"id":25,"enm":"College of Physical Education","or_seq":"580","up":"A10081","nm":"체육대학","cd":"A05297","gb":"H"},
{"id":26,"enm":"Major Convergence","or_seq":"600","up":"A10081","nm":"융합","cd":"A10158","gb":"H"},
{"id":27,"enm":"Convergence","or_seq":"605","up":"A10081","nm":"융합(서울)","cd":"A10671","gb":"H"},
{"id":28,"enm":"후마니타스칼리지교육과정(서울)","or_seq":"610","up":"A10081","nm":"후마니타스칼리지교육과정(서울)","cd":"A10259","gb":"H"},
{"id":29,"enm":"후마니타스칼리지교육과정(국제)","or_seq":"620","up":"A10081","nm":"후마니타스칼리지교육과정(국제)","cd":"A10258","gb":"H"},
{"id":30,"enm":"경희사이버대학(학점교류)-서울","or_seq":"1390","up":"A10081","nm":"경희사이버대학(학점교류)-서울","cd":"A01176","gb":"H"},
{"id":31,"enm":"Others","or_seq":"1410","up":"A10081","nm":"기타(서울)","cd":"A01179","gb":"H"},
{"id":32,"enm":"자연계열","or_seq":"2290","up":"A10081","nm":"자연계열","cd":"A05418","gb":"H"},
{"id":33,"enm":"경희사이버대학(학점교류)-국제","or_seq":"2300","up":"A10081","nm":"경희사이버대학(학점교류)-국제","cd":"A05519","gb":"H"},
{"id":34,"enm":"Others","or_seq":"2310","up":"A10081","nm":"기타(국제)","cd":"A05522","gb":"H"},
{"id":35,"enm":"Graduate School","or_seq":"10","up":"A10014","nm":"대학원","cd":"A01205","gb":"D"},
{"id":36,"enm":"Graduate School of East-West Medical Science","or_seq":"20","up":"A10014","nm":"동서의학대학원","cd":"A06502","gb":"D"},
{"id":37,"enm":"Graduate School of Pan-Pacific International Studies","or_seq":"30","up":"A10014","nm":"국제대학원","cd":"A06573","gb":"D"},
{"id":38,"enm":"Graduate School of Physical Education","or_seq":"40","up":"A10014","nm":"체육대학원","cd":"A06842","gb":"D"},
{"id":39,"enm":"School of Law","or_seq":"70","up":"A10014","nm":"법학전문대학원","cd":"A03687","gb":"D"},
{"id":40,"enm":"The Graduate School of Business Administration","or_seq":"100","up":"A10014","nm":"경영대학원","cd":"A02745","gb":"D"},
{"id":41,"enm":"Graduate School of Education","or_seq":"110","up":"A10014","nm":"교육대학원","cd":"A10083","gb":"D"},
{"id":42,"enm":"Graduate School of Public Policy and Civic Engagement","or_seq":"120","up":"A10014","nm":"공공대학원","cd":"A03692","gb":"D"},
{"id":43,"enm":"Graduate Institute of Peace Studies","or_seq":"130","up":"A10014","nm":"평화복지대학원","cd":"A03375","gb":"D"},
{"id":44,"enm":"Graduate School of Technology Management","or_seq":"140","up":"A10014","nm":"테크노경영대학원","cd":"A06954","gb":"D"},
{"id":45,"enm":"Graduate School of Media & Communication","or_seq":"150","up":"A10014","nm":"미디어커뮤니케이션대학원","cd":"A10486","gb":"D"},
{"id":46,"enm":"Graduate School of International Legal Affairs","or_seq":"160","up":"A10014","nm":"법무대학원","cd":"A03724","gb":"D"},
{"id":47,"enm":"Graduate School of Tourism","or_seq":"170","up":"A10014","nm":"관광대학원","cd":"A03583","gb":"D"},
{"id":48,"enm":"Graduate School of Nursing","or_seq":"175","up":"A10014","nm":"간호대학원","cd":"A10587","gb":"D"},
{"id":49,"enm":"Graduate School of Art&Fusion Design","or_seq":"180","up":"A10014","nm":"아트퓨전디자인대학원","cd":"A06895","gb":"D"}
]
}

major_202210 = {"rows":[
{"id":1,"enm":"College of Law School of Law  Law","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"법과대학 법학부 법학전공","cd":"A00409","gb":"H","dh":"A00400"},
{"id":2,"enm":"College of Politics & Economics Department of International Commerce, Finance, and Investment","orgnz_outpt_ord":"60","orgnz_lvl_se_code":"20","nm":"정경대학 국제통상·금융투자학부","cd":"A10451","gb":"H","dh":"A00422"},
{"id":3,"enm":"College of Politics & Economics Department of Economics Economics","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"정경대학 경제학과 경제학","cd":"A00430","gb":"H","dh":"A00422"},
{"id":4,"enm":"College of Politics & Economics Department of International Trades International Business & Trade","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"정경대학 무역학과 무역학","cd":"A00446","gb":"H","dh":"A00422"},
{"id":5,"enm":"College of Politics & Economics Department of Political Science Political Science & International Relations","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"정경대학 정치외교학과 정치외교학","cd":"A00473","gb":"H","dh":"A00422"},
{"id":6,"enm":"College of Politics & Economics Department of Public Administration Public Administration","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"정경대학 행정학과 행정학","cd":"A00480","gb":"H","dh":"A00422"},
{"id":7,"enm":"College of Politics & Economics Department of Sociology Sociology","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"정경대학 사회학과 사회학","cd":"A00494","gb":"H","dh":"A00422"},
{"id":8,"enm":"College of Politics & Economics Department of Media Media","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"30","nm":"정경대학 미디어학과 미디어학","cd":"A10470","gb":"H","dh":"A00422"},
{"id":9,"enm":"College of Human Ecology","orgnz_outpt_ord":"60","orgnz_lvl_se_code":"11","nm":"생활과학대학","cd":"A00556","gb":"H","dh":"A00556"},
{"id":10,"enm":"College of Human Ecology Department of Housing & Interior Design Major Housing & Interior Design","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"생활과학대학 주거환경학과 주거환경학","cd":"A00579","gb":"H","dh":"A00556"},
{"id":11,"enm":"College of Human Ecology Department of Child & Family Studies Child & Family Studies","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"생활과학대학 아동가족학과 아동가족학","cd":"A00574","gb":"H","dh":"A00556"},
{"id":12,"enm":"College of Human Ecology Department of Clothing and Textiles Clothing and Textiles","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"생활과학대학 의상학과 의상학","cd":"A00571","gb":"H","dh":"A00556"},
{"id":13,"enm":"College of Human Ecology Department of Food and Nutrition Food and Nutrition","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"생활과학대학 식품영양학과 식품영양학","cd":"A00566","gb":"H","dh":"A00556"},
{"id":14,"enm":"College of Medicine  Department of Medicine Medicine","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"의과대학 의학과 의학전공","cd":"A00596","gb":"H","dh":"A00585"},
{"id":15,"enm":"College of Medicine  Department of Premedical course Premedical course","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"의과대학 의예과 의예전공","cd":"A00598","gb":"H","dh":"A00585"},
{"id":16,"enm":"College of Korean Medicine","orgnz_outpt_ord":"75","orgnz_lvl_se_code":"11","nm":"한의과대학","cd":"A00613","gb":"H","dh":"A00613"},
{"id":17,"enm":"College of Korean Medicine Department of Korean Medicine Korean Medicine","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"한의과대학 한의학과 한의학전공","cd":"A00615","gb":"H","dh":"A00613"},
{"id":18,"enm":"College of Korean Medicine Department of Pre-Korean Medicine Premedical course for Korean Medicine","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"한의과대학 한의예과 한의예","cd":"A00617","gb":"H","dh":"A00613"},
{"id":19,"enm":"College of Dentistry Department of Dentistry Dentistry","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"치과대학 치의학과 치의학전공","cd":"A00624","gb":"H","dh":"A00622"},
{"id":20,"enm":"College of Dentistry Department of Premedical course for Dentistry Premedical course for Dentistry","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"치과대학 치의예과 치의예전공","cd":"A00626","gb":"H","dh":"A00622"},
{"id":21,"enm":"College of Pharmacy Department of Oriental Pharmacy Oriental Pharmaceutical Sciences","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"약학대학 한약학과 한약학","cd":"A00636","gb":"H","dh":"A00632"},
{"id":22,"enm":"College of Pharmacy Department of Pharmaceutical Sciences Pharmaceutical Sciences","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"약학대학 약과학과 약과학","cd":"A00638","gb":"H","dh":"A00632"},
{"id":23,"enm":"College of Pharmacy Department of Pharmaceutical Science Pharmacy","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"약학대학 약학과(2+4년제) 약학전공","cd":"A00640","gb":"H","dh":"A00632"},
{"id":24,"enm":"College of Pharmacy Department of Pharmacy Pharmacy","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"약학대학 약학과(6년제) 약학","cd":"A10680","gb":"H","dh":"A00632"},
{"id":25,"enm":"College of Pharmacy College of Pharmacy","orgnz_outpt_ord":"50","orgnz_lvl_se_code":"99","nm":"약학대학 약학대학공통","cd":"A00641","gb":"H","dh":"A00632"},
{"id":26,"enm":"College of Music","orgnz_outpt_ord":"100","orgnz_lvl_se_code":"11","nm":"음악대학","cd":"A00645","gb":"H","dh":"A00645"},
{"id":27,"enm":"College of Music Department of Orchestral Instruments and Piano Musical Instrument","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"음악대학 기악과 기악","cd":"A00651","gb":"H","dh":"A00645"},
{"id":28,"enm":"College of Music Department of Voice Vocal Music","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"음악대학 성악과 성악","cd":"A00654","gb":"H","dh":"A00645"},
{"id":29,"enm":"College of Music Department of Composition Composition","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"음악대학 작곡과 작곡","cd":"A00658","gb":"H","dh":"A00645"},
{"id":30,"enm":"College of Hotel and Tourism Management","orgnz_outpt_ord":"40","orgnz_lvl_se_code":"11","nm":"호텔관광대학","cd":"A00681","gb":"H","dh":"A00681"},
{"id":31,"enm":"College of Hotel and Tourism Management School of Tourism","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"20","nm":"호텔관광대학 관광학부","cd":"A00682","gb":"H","dh":"A00681"},
{"id":32,"enm":"College of Hotel and Tourism Management School of Hospitality Management","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"20","nm":"호텔관광대학 Hospitality경영학부","cd":"A00725","gb":"H","dh":"A00681"},
{"id":33,"enm":"College of Hotel and Tourism Management Department of Culture & Tourism Industry","orgnz_outpt_ord":"170","orgnz_lvl_se_code":"21","nm":"호텔관광대학 문화관광산업학과","cd":"A00730","gb":"H","dh":"A00681"},
{"id":34,"enm":"College of Hotel and Tourism Management Department of Culinary Arts Management","orgnz_outpt_ord":"180","orgnz_lvl_se_code":"21","nm":"호텔관광대학 조리산업학과","cd":"A00732","gb":"H","dh":"A00681"},
{"id":35,"enm":"College of Hotel and Tourism Management School of Hospitality Management Hotel Management","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"호텔관광대학 Hospitality경영학부 호텔경영학과","cd":"A00726","gb":"H","dh":"A00681"},
{"id":36,"enm":"College of Hotel and Tourism Management School of Hospitality Management Convention Management","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"호텔관광대학 Hospitality경영학부 컨벤션경영학과","cd":"A00727","gb":"H","dh":"A00681"},
{"id":37,"enm":"College of Hotel and Tourism Management School of Hospitality Management Foodservice Management","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"30","nm":"호텔관광대학 Hospitality경영학부 외식경영학과","cd":"A00728","gb":"H","dh":"A00681"},
{"id":38,"enm":"College of Hotel and Tourism Management School of Hospitality Management Culinary Art & Foodservice Management","orgnz_outpt_ord":"40","orgnz_lvl_se_code":"30","nm":"호텔관광대학 Hospitality경영학부 조리·서비스경영학과","cd":"A00729","gb":"H","dh":"A00681"},
{"id":39,"enm":"College of Hotel and Tourism Management School of Tourism Culture, Tourism & Content","orgnz_outpt_ord":"70","orgnz_lvl_se_code":"30","nm":"호텔관광대학 관광학부 문화관광콘텐츠학과","cd":"A00692","gb":"H","dh":"A00681"},
{"id":40,"enm":"College of Hotel and Tourism Management School of Tourism Tourism Sciences","orgnz_outpt_ord":"90","orgnz_lvl_se_code":"30","nm":"호텔관광대학 관광학부 관광학과","cd":"A00694","gb":"H","dh":"A00681"},
{"id":41,"enm":"College of Humanities Department of English Language and Literature English Linguistics and Literature","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"문과대학 영어영문학과 영어영문학","cd":"A07315","gb":"H","dh":"A01008"},
{"id":42,"enm":"College of Humanities Department of Applied English Language and Translation Studies Applied English Linguistics and Translation Studies","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"문과대학 응용영어통번역학과 응용영어통번역학","cd":"A07302","gb":"H","dh":"A01008"},
{"id":43,"enm":"College of Humanities Department of Philosophy Philosophy","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"문과대학 철학과 철학","cd":"A01015","gb":"H","dh":"A01008"},
{"id":44,"enm":"College of Humanities Department of History History","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"문과대학 사학과 사학","cd":"A01012","gb":"H","dh":"A01008"},
{"id":45,"enm":"College of Humanities Department of Korean Language and Literature Korean Language and Literature","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"문과대학 국어국문학과 국어국문학","cd":"A01010","gb":"H","dh":"A01008"},
{"id":46,"enm":"College of Business Administration","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"11","nm":"경영대학","cd":"A01024","gb":"H","dh":"A01024"},
{"id":47,"enm":"College of Business Administration Department of Accounting and Taxation Accounting and Taxation","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"경영대학 회계ㆍ세무학과 회계ㆍ세무학","cd":"A01039","gb":"H","dh":"A01024"},
{"id":48,"enm":"College of Business Administration Business Administration Business Administration","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"경영대학 경영학과 경영학","cd":"A01041","gb":"H","dh":"A01024"},
{"id":49,"enm":"College of Business Administration Department of Big Data Analytics Big Data Analytics","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"경영대학 빅데이터응용학과 빅데이터응용학","cd":"A10679","gb":"H","dh":"A01024"},
{"id":50,"enm":"College of Sciences Department of Biology Biology","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"이과대학 생물학과 생물학","cd":"A01070","gb":"H","dh":"A01043"},
{"id":51,"enm":"College of Sciences Department of Chemistry Chemistry","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"이과대학 화학과 화학","cd":"A01068","gb":"H","dh":"A01043"},
{"id":52,"enm":"College of Sciences Department of Physics Physics","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"이과대학 물리학과 물리학","cd":"A01065","gb":"H","dh":"A01043"},
{"id":53,"enm":"College of Sciences Department of Mathematics Mathematics","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"이과대학 수학과 수학","cd":"A01063","gb":"H","dh":"A01043"},
{"id":54,"enm":"College of Sciences Department of Information Display Information Display","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"이과대학 정보디스플레이학과 정보디스플레이학","cd":"A01059","gb":"H","dh":"A01043"},
{"id":55,"enm":"College of Sciences Department of Geography Geography","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"이과대학 지리학과 지리학","cd":"A01050","gb":"H","dh":"A01043"},
{"id":56,"enm":"College of Nursing Science Department of Nursing Nursing","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"간호과학대학 간호학과 간호학","cd":"A01080","gb":"H","dh":"A01074"},
{"id":57,"enm":"College of Nursing Science Department of Nursing Nursing","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"30","nm":"간호과학대학 간호학과(야) 간호학전공","cd":"A01082","gb":"H","dh":"A01074"},
{"id":58,"enm":"College of Fine Arts School of Fine Art","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"20","nm":"미술대학 미술학부","cd":"A01086","gb":"H","dh":"A01085"},
{"id":59,"enm":"College of Fine Arts School of Fine Art Korean Painting","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"미술대학 미술학부 한국화","cd":"A01087","gb":"H","dh":"A01085"},
{"id":60,"enm":"College of Fine Arts School of Fine Art Painting","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"미술대학 미술학부 회화","cd":"A01088","gb":"H","dh":"A01085"},
{"id":61,"enm":"College of Fine Arts School of Fine Art Sculpture","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"30","nm":"미술대학 미술학부 조소","cd":"A01089","gb":"H","dh":"A01085"},
{"id":62,"enm":"School of Dance School of Dance","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"20","nm":"무용학부 무용학부","cd":"A01102","gb":"H","dh":"A01101"},
{"id":63,"enm":"School of Dance School of Dance Korean Dance","orgnz_outpt_ord":"40","orgnz_lvl_se_code":"30","nm":"무용학부 무용학부 한국무용","cd":"A01103","gb":"H","dh":"A01101"},
{"id":64,"enm":"School of Dance School of Dance Contemporary Dance","orgnz_outpt_ord":"50","orgnz_lvl_se_code":"30","nm":"무용학부 무용학부 현대무용","cd":"A01104","gb":"H","dh":"A01101"},
{"id":65,"enm":"School of Dance School of Dance Ballet","orgnz_outpt_ord":"60","orgnz_lvl_se_code":"30","nm":"무용학부 무용학부 발레","cd":"A01105","gb":"H","dh":"A01101"},
{"id":66,"enm":"경희사이버대학(학점교류)-서울 경희사이버대학(학점교류) 경희사이버대학(학점교류)","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"경희사이버대학(학점교류)-서울 경희사이버대학(학점교류) 경희사이버대학(학점교류)","cd":"A01178","gb":"H","dh":"A01176"},
{"id":67,"enm":"Others","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"기타(서울) ROTC과정 군사학","cd":"A01181","gb":"H","dh":"A01179"},
{"id":68,"enm":"Others","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"기타(서울) 취업스쿨 취업관련강좌","cd":"A01185","gb":"H","dh":"A01179"},
{"id":69,"enm":"Others International Exchange Student International exchange student","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"기타(서울) 국교위교환학생 국교위교환학생전공","cd":"A01189","gb":"H","dh":"A01179"},
{"id":70,"enm":"Others","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"기타(서울) 사회봉사 사회봉사관련강좌","cd":"A01191","gb":"H","dh":"A01179"},
{"id":71,"enm":"Graduate School","orgnz_outpt_ord":"2130","orgnz_lvl_se_code":"21","nm":"대학원 융합교육강좌","cd":"A10588","gb":"H","dh":"A01205"},
{"id":72,"enm":"Graduate School Department of Integrated Drug Development and Natural Products","orgnz_outpt_ord":"2170","orgnz_lvl_se_code":"21","nm":"대학원 천연물융합신약개발학과","cd":"A10699","gb":"H","dh":"A01205"},
{"id":73,"enm":"College of Foreign Language & Literature School of Global Communication","orgnz_outpt_ord":"40","orgnz_lvl_se_code":"20","nm":"외국어대학 글로벌커뮤니케이션학부","cd":"A04674","gb":"H","dh":"A04620"},
{"id":74,"enm":"College of Foreign Language & Literature Department of Japanese","orgnz_outpt_ord":"90","orgnz_lvl_se_code":"21","nm":"외국어대학 일본어학과","cd":"A04670","gb":"H","dh":"A04620"},
{"id":75,"enm":"College of Foreign Language & Literature School of Global Communication British-American Language and Literature","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"외국어대학 글로벌커뮤니케이션학부 영미어문","cd":"A04675","gb":"H","dh":"A04620"},
{"id":76,"enm":"College of Foreign Language & Literature Department of Korean Korean","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"외국어대학 한국어학과 한국어학","cd":"A04673","gb":"H","dh":"A04620"},
{"id":77,"enm":"College of Foreign Language & Literature Chinese Language and Literature Chinese Language and Literature","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"외국어대학 중국어학과 중국어학","cd":"A04669","gb":"H","dh":"A04620"},
{"id":78,"enm":"College of Foreign Language & Literature Department of Russian Russian","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"외국어대학 러시아어학과 러시아어학","cd":"A04667","gb":"H","dh":"A04620"},
{"id":79,"enm":"College of Foreign Language & Literature Department of Spanish Spanish","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"외국어대학 스페인어학과 스페인어학","cd":"A04665","gb":"H","dh":"A04620"},
{"id":80,"enm":"College of Foreign Language & Literature Department of French French","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"외국어대학 프랑스어학과 프랑스어학","cd":"A04663","gb":"H","dh":"A04620"},
{"id":81,"enm":"College of Foreign Language & Literature School of Global Communication British-American Culture","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"외국어대학 글로벌커뮤니케이션학부 영미문화","cd":"A04676","gb":"H","dh":"A04620"},
{"id":82,"enm":"College of Engineering Department of Environmental Science and Engineering","orgnz_outpt_ord":"130","orgnz_lvl_se_code":"21","nm":"공과대학 환경학및환경공학과","cd":"A04847","gb":"H","dh":"A04754"},
{"id":83,"enm":"College of Engineering Department of Architectural Engineering Architectural Engineering","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공과대학 건축공학과 건축공학","cd":"A04756","gb":"H","dh":"A04754"},
{"id":84,"enm":"College of Engineering Department of Mechanical Engineering Mechanical Engineering","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공과대학 기계공학과 기계공학","cd":"A04764","gb":"H","dh":"A04754"},
{"id":85,"enm":"College of Engineering Department of Civil Engineering Civil Engineering","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공과대학 사회기반시스템공학과 사회기반시스템공학","cd":"A04818","gb":"H","dh":"A04754"},
{"id":86,"enm":"College of Engineering Department of Chemical Engineering Chemical Engineering","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공과대학 화학공학과 화학공학","cd":"A04820","gb":"H","dh":"A04754"},
{"id":87,"enm":"College of Engineering Department of Architecture Architecture","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공과대학 건축학과 건축학","cd":"A04838","gb":"H","dh":"A04754"},
{"id":88,"enm":"College of Engineering Department of Industrial & Management Systems Engineering Industrial & Management Systems Engineering","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공과대학 산업경영공학과 산업경영공학","cd":"A04840","gb":"H","dh":"A04754"},
{"id":89,"enm":"College of Engineering Department of Advanced Materials Engineering for Information & Electronics Advanced Materials Engineering for Information & Electronics","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공과대학 정보전자신소재공학과 정보전자신소재공학","cd":"A04845","gb":"H","dh":"A04754"},
{"id":90,"enm":"College of Engineering Department of Environmental Science and Engineering Environmental Science","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공과대학 환경학및환경공학과 환경학","cd":"A04848","gb":"H","dh":"A04754"},
{"id":91,"enm":"College of Engineering Department of Nuclear Engineering Nuclear Engineering","orgnz_outpt_ord":"40","orgnz_lvl_se_code":"30","nm":"공과대학 원자력공학과 원자력공학","cd":"A04783","gb":"H","dh":"A04754"},
{"id":92,"enm":"College of Electronics and Information Electronic Engineering Electronic Engineering","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"전자정보대학 전자공학과 전자공학","cd":"A05129","gb":"H","dh":"A05091"},
{"id":93,"enm":"College of Electronics and Information Department of Biomedical Engineering Biomedical Engineering","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"전자정보대학 생체의공학과 생체의공학","cd":"A05127","gb":"H","dh":"A05091"},
{"id":94,"enm":"College of Life Sciences","orgnz_outpt_ord":"540","orgnz_lvl_se_code":"11","nm":"생명과학대학","cd":"A05165","gb":"H","dh":"A05165"},
{"id":95,"enm":"College of Life Sciences Department of Plant and Environmental New Resources  Plant and Environmental New Resources","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"생명과학대학 식물·환경신소재공학과 식물·환경신소재공학","cd":"A05187","gb":"H","dh":"A05165"},
{"id":96,"enm":"College of Life Sciences Department of Food Science & BIOtechnology Food Science & Biotechnology","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"생명과학대학 식품생명공학과 식품생명공학","cd":"A05192","gb":"H","dh":"A05165"},
{"id":97,"enm":"College of Life Sciences Oriental Medicine Biotechnology Oriental Medicine Biotechnology","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"생명과학대학 한방생명공학과 한방생명공학","cd":"A10459","gb":"H","dh":"A05165"},
{"id":98,"enm":"College of Life Sciences Department of Genetic Engineering Genetic Engineering","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"생명과학대학 유전생명공학과 유전생명공학","cd":"A10460","gb":"H","dh":"A05165"},
{"id":99,"enm":"College of Life Sciences Department of Smart Farm Science Smart Farm Science","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"생명과학대학 스마트팜과학과 스마트팜과학","cd":"A10625","gb":"H","dh":"A05165"},
{"id":100,"enm":"College of Management and International Relations Division of Management & Int'l Relations Global Management","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"국제·경영대학 국제경영학부 국제경영전공","cd":"A05210","gb":"H","dh":"A05208"},
{"id":101,"enm":"College of Art & Design","orgnz_outpt_ord":"570","orgnz_lvl_se_code":"11","nm":"예술·디자인대학","cd":"A05240","gb":"H","dh":"A05240"},
{"id":102,"enm":"College of Art & Design Department of Ceramic Art Ceramic Arts","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"예술·디자인대학 도예학과 도예학","cd":"A05254","gb":"H","dh":"A05240"},
{"id":103,"enm":"College of Art & Design Department of Post Modern Music Post Modern Music","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"예술·디자인대학 Post Modern음악학과 Post Modern음악학","cd":"A05272","gb":"H","dh":"A05240"},
{"id":104,"enm":"College of Art & Design Department of Theater & Film Theater & Film","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"예술·디자인대학 연극영화학과 연극영화학","cd":"A05276","gb":"H","dh":"A05240"},
{"id":105,"enm":"College of Art & Design Department of Industrial Design Industrial Design","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"예술·디자인대학 산업디자인학과 산업디자인학","cd":"A05280","gb":"H","dh":"A05240"},
{"id":106,"enm":"College of Art & Design Department of Landscape Architecture Landscape Architecture","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"예술·디자인대학 환경조경디자인학과 환경조경디자인학","cd":"A05285","gb":"H","dh":"A05240"},
{"id":107,"enm":"College of Art & Design Department of Textile & Clothing Design Textile & Clothing Design","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"예술·디자인대학 의류디자인학과 의류디자인학","cd":"A05287","gb":"H","dh":"A05240"},
{"id":108,"enm":"College of Art & Design Department of Digital Contents Digital Contents","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"예술·디자인대학 디지털콘텐츠학과 디지털콘텐츠학","cd":"A05289","gb":"H","dh":"A05240"},
{"id":109,"enm":"College of Art & Design Department of Visual Design Visual Design","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"예술·디자인대학 시각디자인학과 시각디자인학","cd":"A05294","gb":"H","dh":"A05240"},
{"id":110,"enm":"College of Physical Education","orgnz_outpt_ord":"580","orgnz_lvl_se_code":"11","nm":"체육대학","cd":"A05297","gb":"H","dh":"A05297"},
{"id":111,"enm":"College of Physical Education Major in TaeKwonDo Major in TaeKwonDo","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"체육대학 태권도학과 태권도학","cd":"A05307","gb":"H","dh":"A05297"},
{"id":112,"enm":"College of Physical Education Physical Education Physical Education","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"체육대학 체육학과 체육학","cd":"A05317","gb":"H","dh":"A05297"},
{"id":113,"enm":"College of Physical Education Sports Medicine Sports Medicine","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"체육대학 스포츠의학과 스포츠의학","cd":"A05319","gb":"H","dh":"A05297"},
{"id":114,"enm":"College of Physical Education Sports Coaching Sports Coaching","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"체육대학 스포츠지도학과 스포츠지도학","cd":"A05324","gb":"H","dh":"A05297"},
{"id":115,"enm":"College of Physical Education Department of Golf Industry Golf Industry","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"체육대학 골프산업학과 골프산업학","cd":"A05326","gb":"H","dh":"A05297"},
{"id":116,"enm":"College of Applied Science Astronomy and Space Science Astronomy and Space Science","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"응용과학대학 우주과학과 우주과학","cd":"A05363","gb":"H","dh":"A05346"},
{"id":117,"enm":"College of Applied Science Applied Chemistry Applied Chemistry","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"응용과학대학 응용화학과 응용화학","cd":"A05361","gb":"H","dh":"A05346"},
{"id":118,"enm":"College of Applied Science Applied Physics Applied Physics","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"응용과학대학 응용물리학과 응용물리학","cd":"A05357","gb":"H","dh":"A05346"},
{"id":119,"enm":"College of Applied Science Applied Mathematics Applied Mathematics","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"응용과학대학 응용수학과 응용수학","cd":"A05355","gb":"H","dh":"A05346"},
{"id":120,"enm":"College of International Studies Department of Global Korean Studies Global Korean Studies","orgnz_outpt_ord":"5","orgnz_lvl_se_code":"30","nm":"국제대학 글로벌한국학과 글로벌한국학","cd":"A10296","gb":"H","dh":"A05366"},
{"id":121,"enm":"College of International Studies Department of International Studies International Studies","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"국제대학 국제학과 국제학","cd":"A05368","gb":"H","dh":"A05366"},
{"id":122,"enm":"자연계열","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"자연계열 전공기초 전공기초(수학)","cd":"A05420","gb":"H","dh":"A05418"},
{"id":123,"enm":"자연계열","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"자연계열 전공기초 전공기초(물리)","cd":"A05421","gb":"H","dh":"A05418"},
{"id":124,"enm":"자연계열","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"30","nm":"자연계열 전공기초 전공기초(화학)","cd":"A05422","gb":"H","dh":"A05418"},
{"id":125,"enm":"자연계열","orgnz_outpt_ord":"40","orgnz_lvl_se_code":"30","nm":"자연계열 전공기초 전공기초(생물1)","cd":"A05423","gb":"H","dh":"A05418"},
{"id":126,"enm":"자연계열","orgnz_outpt_ord":"50","orgnz_lvl_se_code":"30","nm":"자연계열 전공기초 전공기초(생물2)","cd":"A05424","gb":"H","dh":"A05418"},
{"id":127,"enm":"경희사이버대학(학점교류)-국제 경희사이버대학(학점교류) 경희사이버대학(학점교류)","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"경희사이버대학(학점교류)-국제 경희사이버대학(학점교류) 경희사이버대학(학점교류)","cd":"A05521","gb":"H","dh":"A05519"},
{"id":128,"enm":"Others","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"기타(국제) ROTC과정 군사학","cd":"A05524","gb":"H","dh":"A05522"},
{"id":129,"enm":"Others","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"기타(국제) 취업스쿨 취업관련강좌","cd":"A05528","gb":"H","dh":"A05522"},
{"id":130,"enm":"Others","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"기타(국제) 사회봉사 사회봉사관련강좌","cd":"A05544","gb":"H","dh":"A05522"},
{"id":131,"enm":"College of Software School of Computer Science and Engineering Department of Computer Science and Engineering","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"소프트웨어융합대학 컴퓨터공학부 컴퓨터공학과","cd":"A10627","gb":"H","dh":"A07340"},
{"id":132,"enm":"College of Software Software Convergence Software Convergence","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"소프트웨어융합대학 소프트웨어융합학과 소프트웨어융합학","cd":"A07337","gb":"H","dh":"A07340"},
{"id":133,"enm":"College of Software School of Computer Science and Engineering Department of Artificial Intelligence","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"소프트웨어융합대학 컴퓨터공학부 인공지능학과","cd":"A10628","gb":"H","dh":"A07340"},
{"id":134,"enm":"College of Software Department of Computer Science and Engineering Computer Science and Engineering","orgnz_outpt_ord":"40","orgnz_lvl_se_code":"30","nm":"소프트웨어융합대학 컴퓨터공학과 컴퓨터공학","cd":"A07308","gb":"H","dh":"A07340"},
{"id":135,"enm":"Major Convergence Smart Farm Engineering Convergence Major Smart Farm Engineering Convergence Major","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"융합 스마트팜공학 스마트팜공학융합전공","cd":"A10168","gb":"H","dh":"A10158"},
{"id":136,"enm":"Major Convergence Art & Technology Convergence Major Art & Technology Convergence Major","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"융합 아트&테크놀로지 아트&테크놀로지융합전공","cd":"A10167","gb":"H","dh":"A10158"},
{"id":137,"enm":"Major Convergence 4D ART Convergence Major 4D ART Convergence Major","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"융합 4D아트 4D아트융합전공","cd":"A10166","gb":"H","dh":"A10158"},
{"id":138,"enm":"Major Convergence Global Engineering Convergence Major Global Engineering Convergence Major","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"융합 글로벌엔지니어링 글로벌엔지니어링융합전공","cd":"A10164","gb":"H","dh":"A10158"},
{"id":139,"enm":"Major Convergence Global Culture Technology Major Global Culture Technology Major","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"융합 글로벌문화기술 글로벌문화기술융합전공","cd":"A10165","gb":"H","dh":"A10158"},
{"id":140,"enm":"후마니타스칼리지교육과정(국제) Core Requirements English","orgnz_outpt_ord":"110","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 필수교과 영어","cd":"A10144","gb":"H","dh":"A10258"},
{"id":141,"enm":"후마니타스칼리지교육과정(국제) Core Requirements Expository wrting","orgnz_outpt_ord":"120","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 필수교과 글쓰기","cd":"A10145","gb":"H","dh":"A10258"},
{"id":142,"enm":"후마니타스칼리지교육과정(국제) Core Requirements Civilization in Global Context","orgnz_outpt_ord":"130","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 필수교과 문명전개의지구적문맥","cd":"A10146","gb":"H","dh":"A10258"},
{"id":143,"enm":"후마니타스칼리지교육과정(국제)","orgnz_outpt_ord":"210","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 기초교과 영어","cd":"A05403","gb":"H","dh":"A10258"},
{"id":144,"enm":"후마니타스칼리지교육과정(국제)","orgnz_outpt_ord":"220","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 기초교과 글쓰기","cd":"A05402","gb":"H","dh":"A10258"},
{"id":145,"enm":"후마니타스칼리지교육과정(국제)","orgnz_outpt_ord":"230","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 기초교과 시민교육","cd":"A05401","gb":"H","dh":"A10258"},
{"id":146,"enm":"후마니타스칼리지교육과정(국제) Distribution Requirements Foundations in Creative Arts","orgnz_outpt_ord":"410","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 배분이수교과 예술창작토대","cd":"A10147","gb":"H","dh":"A10258"},
{"id":147,"enm":"후마니타스칼리지교육과정(국제) Distribution Requirements Foundations in the Humanities and Social Sciences","orgnz_outpt_ord":"420","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 배분이수교과 인문사회토대","cd":"A10148","gb":"H","dh":"A10258"},
{"id":148,"enm":"후마니타스칼리지교육과정(국제) Distribution Requirements Foundations in Science and Technology","orgnz_outpt_ord":"430","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 배분이수교과 자연기술토대","cd":"A10149","gb":"H","dh":"A10258"},
{"id":149,"enm":"후마니타스칼리지교육과정(국제) Distribution Requirements Society and Peace","orgnz_outpt_ord":"440","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 배분이수교과 사회와평화","cd":"A10150","gb":"H","dh":"A10258"},
{"id":150,"enm":"후마니타스칼리지교육과정(국제) Distribution Requirements Symbols and Culture","orgnz_outpt_ord":"450","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 배분이수교과 상징과문화","cd":"A10151","gb":"H","dh":"A10258"},
{"id":151,"enm":"후마니타스칼리지교육과정(국제) Distribution Requirements Analysis and Mathematical Reasoning","orgnz_outpt_ord":"460","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 배분이수교과 분석과추론","cd":"A10152","gb":"H","dh":"A10258"},
{"id":152,"enm":"후마니타스칼리지교육과정(국제) Distribution Requirements Life and the Cosmos","orgnz_outpt_ord":"470","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 배분이수교과 생명과우주","cd":"A10153","gb":"H","dh":"A10258"},
{"id":153,"enm":"후마니타스칼리지교육과정(국제)  Physical Education","orgnz_outpt_ord":"540","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 자유이수 체육","cd":"A05408","gb":"H","dh":"A10258"},
{"id":154,"enm":"후마니타스칼리지교육과정(국제)","orgnz_outpt_ord":"550","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 자유이수 자유이수 기타","cd":"A05405","gb":"H","dh":"A10258"},
{"id":155,"enm":"후마니타스칼리지교육과정(국제)","orgnz_outpt_ord":"560","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 자유이수 자유이수교과(기숙교육프로그램)","cd":"A05406","gb":"H","dh":"A10258"},
{"id":156,"enm":"후마니타스칼리지교육과정(국제)","orgnz_outpt_ord":"710","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(국제) 교직전공 교직전공","cd":"A05381","gb":"H","dh":"A10258"},
{"id":157,"enm":"후마니타스칼리지교육과정(서울)","orgnz_outpt_ord":"80","orgnz_lvl_se_code":"21","nm":"후마니타스칼리지교육과정(서울) 교직전공","cd":"A01113","gb":"H","dh":"A10259"},
{"id":158,"enm":"후마니타스칼리지교육과정(서울) Core Requirements English","orgnz_outpt_ord":"110","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 필수교과 영어","cd":"A10133","gb":"H","dh":"A10259"},
{"id":159,"enm":"후마니타스칼리지교육과정(서울) Core Requirements Expository wrting","orgnz_outpt_ord":"120","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 필수교과 글쓰기","cd":"A10132","gb":"H","dh":"A10259"},
{"id":160,"enm":"후마니타스칼리지교육과정(서울) Core Requirements Civilization in Global Context","orgnz_outpt_ord":"130","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 필수교과 문명전개의지구적문맥","cd":"A10131","gb":"H","dh":"A10259"},
{"id":161,"enm":"후마니타스칼리지교육과정(서울) Required Fundamentals","orgnz_outpt_ord":"220","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 기초교과 글쓰기","cd":"A01135","gb":"H","dh":"A10259"},
{"id":162,"enm":"후마니타스칼리지교육과정(서울) Required Fundamentals Civic Education","orgnz_outpt_ord":"240","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 기초교과 시민교육","cd":"A01134","gb":"H","dh":"A10259"},
{"id":163,"enm":"후마니타스칼리지교육과정(서울) Distribution Requirements Life and the Cosmos","orgnz_outpt_ord":"410","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 배분이수교과 생명과우주","cd":"A10135","gb":"H","dh":"A10259"},
{"id":164,"enm":"후마니타스칼리지교육과정(서울) Distribution Requirements Analysis and Mathematical Reasoning","orgnz_outpt_ord":"420","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 배분이수교과 분석과추론","cd":"A10136","gb":"H","dh":"A10259"},
{"id":165,"enm":"후마니타스칼리지교육과정(서울) Distribution Requirements Foundations in Creative Arts","orgnz_outpt_ord":"430","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 배분이수교과 예술창작토대","cd":"A10137","gb":"H","dh":"A10259"},
{"id":166,"enm":"후마니타스칼리지교육과정(서울) Distribution Requirements Foundations in the Humanities and Social Sciences","orgnz_outpt_ord":"440","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 배분이수교과 인문사회토대","cd":"A10138","gb":"H","dh":"A10259"},
{"id":167,"enm":"후마니타스칼리지교육과정(서울) Distribution Requirements Foundations in Science and Technology","orgnz_outpt_ord":"450","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 배분이수교과 자연기술토대","cd":"A10139","gb":"H","dh":"A10259"},
{"id":168,"enm":"후마니타스칼리지교육과정(서울) Distribution Requirements Society and Peace","orgnz_outpt_ord":"460","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 배분이수교과 사회와평화","cd":"A10140","gb":"H","dh":"A10259"},
{"id":169,"enm":"후마니타스칼리지교육과정(서울) Distribution Requirements Symbols and Culture","orgnz_outpt_ord":"470","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 배분이수교과 상징과문화","cd":"A10141","gb":"H","dh":"A10259"},
{"id":170,"enm":"후마니타스칼리지교육과정(서울) Electives Physical Education","orgnz_outpt_ord":"540","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 자유이수교과 체육","cd":"A01141","gb":"H","dh":"A10259"},
{"id":171,"enm":"후마니타스칼리지교육과정(서울) Electives Other Electives","orgnz_outpt_ord":"560","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 자유이수교과 자유이수 기타","cd":"A01138","gb":"H","dh":"A10259"},
{"id":172,"enm":"후마니타스칼리지교육과정(서울) Independent Study Courses Independent Study Courses","orgnz_outpt_ord":"610","orgnz_lvl_se_code":"30","nm":"후마니타스칼리지교육과정(서울) 배움학점제 배움학점제","cd":"A01146","gb":"H","dh":"A10259"},
{"id":173,"enm":"Department of Global Eminence Department of Global Eminence Global Leader","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"자율전공학부 자율전공학부 글로벌리더","cd":"A10468","gb":"H","dh":"A10466"},
{"id":174,"enm":"Department of Global Eminence Department of Global Eminence Global Business","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"자율전공학부 자율전공학부 글로벌비즈니스","cd":"A10469","gb":"H","dh":"A10466"},
{"id":175,"enm":"Convergence Science Information Convergence Major Science Information Convergence Major","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"융합(서울) 과학지능정보 과학지능정보융합전공","cd":"A10678","gb":"H","dh":"A10671"},
{"id":176,"enm":"Convergence Convergence in Social Science Convergence in Social Science","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"40","nm":"융합(서울) 사회과학 사회과학융합전공","cd":"A10675","gb":"H","dh":"A10671"},
{"id":177,"enm":"Graduate School KHU-KIST Department of Converging Science and Technology","orgnz_outpt_ord":"240","orgnz_lvl_se_code":"21","nm":"대학원 KHU-KIST 융합과학기술학과","cd":"A02623","gb":"D","dh":"A01205"},
{"id":178,"enm":"Graduate School Department of Global public health and Korean Medicine Management","orgnz_outpt_ord":"260","orgnz_lvl_se_code":"21","nm":"대학원 글로벌보건한의정책학과","cd":"A02636","gb":"D","dh":"A01205"},
{"id":179,"enm":"Graduate School Department of Software Convergence","orgnz_outpt_ord":"270","orgnz_lvl_se_code":"21","nm":"대학원 소프트웨어융합학과(계약학과)","cd":"A02639","gb":"D","dh":"A01205"},
{"id":180,"enm":"Graduate School Department of Software Convergence","orgnz_outpt_ord":"275","orgnz_lvl_se_code":"21","nm":"대학원 소프트웨어융합학과","cd":"A10276","gb":"D","dh":"A01205"},
{"id":181,"enm":"Graduate School Department of Global Hospitality & Tourism Management","orgnz_outpt_ord":"280","orgnz_lvl_se_code":"21","nm":"대학원 글로벌Hospitality·관광학과","cd":"A02640","gb":"D","dh":"A01205"},
{"id":182,"enm":"Graduate School Department of Biomedical Science and Technology","orgnz_outpt_ord":"290","orgnz_lvl_se_code":"21","nm":"대학원 융합의과학과","cd":"A02642","gb":"D","dh":"A01205"},
{"id":183,"enm":"Graduate School Department of Performing Arts","orgnz_outpt_ord":"300","orgnz_lvl_se_code":"21","nm":"대학원 공연예술학과","cd":"A02317","gb":"D","dh":"A01205"},
{"id":184,"enm":"Graduate School Department of Korean Language and Literature","orgnz_outpt_ord":"490","orgnz_lvl_se_code":"21","nm":"대학원 국어국문학과","cd":"A01317","gb":"D","dh":"A01205"},
{"id":185,"enm":"Graduate School Department of English Language and Literature","orgnz_outpt_ord":"500","orgnz_lvl_se_code":"21","nm":"대학원 영어영문학과","cd":"A01696","gb":"D","dh":"A01205"},
{"id":186,"enm":"Graduate School Applied English Linguistics & Translation Studies","orgnz_outpt_ord":"505","orgnz_lvl_se_code":"21","nm":"대학원 응용영어통번역학과","cd":"A10525","gb":"D","dh":"A01205"},
{"id":187,"enm":"Graduate School Department of British and American Language and Culture","orgnz_outpt_ord":"510","orgnz_lvl_se_code":"21","nm":"대학원 영미어문화학과","cd":"A01692","gb":"D","dh":"A01205"},
{"id":188,"enm":"Graduate School Department of East-Asian Language and Literature","orgnz_outpt_ord":"530","orgnz_lvl_se_code":"21","nm":"대학원 동양어문학과","cd":"A02466","gb":"D","dh":"A01205"},
{"id":189,"enm":"Graduate School Department of European Language and Literature","orgnz_outpt_ord":"540","orgnz_lvl_se_code":"21","nm":"대학원 유럽어문학과","cd":"A02469","gb":"D","dh":"A01205"},
{"id":190,"enm":"Graduate School Department of International Korean Language and Culture","orgnz_outpt_ord":"550","orgnz_lvl_se_code":"21","nm":"대학원 국제한국언어문화학과","cd":"A02474","gb":"D","dh":"A01205"},
{"id":191,"enm":"Graduate School Department of History","orgnz_outpt_ord":"590","orgnz_lvl_se_code":"21","nm":"대학원 사학과","cd":"A01497","gb":"D","dh":"A01205"},
{"id":192,"enm":"Graduate School Department of Philosophy","orgnz_outpt_ord":"600","orgnz_lvl_se_code":"21","nm":"대학원 철학과","cd":"A02045","gb":"D","dh":"A01205"},
{"id":193,"enm":"Graduate School Department of Sociology","orgnz_outpt_ord":"610","orgnz_lvl_se_code":"21","nm":"대학원 사회학과","cd":"A01506","gb":"D","dh":"A01205"},
{"id":194,"enm":"Graduate School Department of Law","orgnz_outpt_ord":"620","orgnz_lvl_se_code":"21","nm":"대학원 법학과","cd":"A01463","gb":"D","dh":"A01205"},
{"id":195,"enm":"Graduate School Department of Public Administration","orgnz_outpt_ord":"630","orgnz_lvl_se_code":"21","nm":"대학원 행정학과","cd":"A02225","gb":"D","dh":"A01205"},
{"id":196,"enm":"Graduate School Department of Political Science","orgnz_outpt_ord":"640","orgnz_lvl_se_code":"21","nm":"대학원 정치학과","cd":"A02005","gb":"D","dh":"A01205"},
{"id":197,"enm":"Graduate School Department of Economics","orgnz_outpt_ord":"660","orgnz_lvl_se_code":"21","nm":"대학원 경제학과","cd":"A01286","gb":"D","dh":"A01205"},
{"id":198,"enm":"Graduate School Department of International Trade","orgnz_outpt_ord":"670","orgnz_lvl_se_code":"21","nm":"대학원 무역학과","cd":"A01408","gb":"D","dh":"A01205"},
{"id":199,"enm":"Graduate School Department of Business Administration","orgnz_outpt_ord":"680","orgnz_lvl_se_code":"21","nm":"대학원 경영학과","cd":"A01260","gb":"D","dh":"A01205"},
{"id":200,"enm":"Graduate School Department of Accounting","orgnz_outpt_ord":"710","orgnz_lvl_se_code":"21","nm":"대학원 회계·세무학과","cd":"A02577","gb":"D","dh":"A01205"},
{"id":201,"enm":"Graduate School Department of Tourism Sciences","orgnz_outpt_ord":"750","orgnz_lvl_se_code":"21","nm":"대학원 관광학과","cd":"A01310","gb":"D","dh":"A01205"},
{"id":202,"enm":"Graduate School Department of Mathematics","orgnz_outpt_ord":"760","orgnz_lvl_se_code":"21","nm":"대학원 수학과","cd":"A01579","gb":"D","dh":"A01205"},
{"id":203,"enm":"Graduate School Department of Culinary Science and Foodservice Management","orgnz_outpt_ord":"770","orgnz_lvl_se_code":"21","nm":"대학원 조리외식경영학과","cd":"A02410","gb":"D","dh":"A01205"},
{"id":204,"enm":"Graduate School Department of Physics","orgnz_outpt_ord":"780","orgnz_lvl_se_code":"21","nm":"대학원 물리학과","cd":"A01425","gb":"D","dh":"A01205"},
{"id":205,"enm":"Graduate School Department of Chemistry","orgnz_outpt_ord":"790","orgnz_lvl_se_code":"21","nm":"대학원 화학과","cd":"A02247","gb":"D","dh":"A01205"},
{"id":206,"enm":"Graduate School Department of Biology","orgnz_outpt_ord":"800","orgnz_lvl_se_code":"21","nm":"대학원 생물학과","cd":"A01548","gb":"D","dh":"A01205"},
{"id":207,"enm":"Graduate School Department of Geography","orgnz_outpt_ord":"810","orgnz_lvl_se_code":"21","nm":"대학원 지리학과","cd":"A02034","gb":"D","dh":"A01205"},
{"id":208,"enm":"Graduate School Graduate School of Biotechnology","orgnz_outpt_ord":"830","orgnz_lvl_se_code":"21","nm":"대학원 생명공학원","cd":"A01537","gb":"D","dh":"A01205"},
{"id":209,"enm":"Graduate School Department of Oriental Medicinal Materials and Processing","orgnz_outpt_ord":"840","orgnz_lvl_se_code":"21","nm":"대학원 한방재료가공학과","cd":"A02324","gb":"D","dh":"A01205"},
{"id":210,"enm":"Graduate School Food Science","orgnz_outpt_ord":"850","orgnz_lvl_se_code":"21","nm":"대학원 식품공학과","cd":"A01612","gb":"D","dh":"A01205"},
{"id":211,"enm":"Graduate School Department of Applied Environmental Science","orgnz_outpt_ord":"880","orgnz_lvl_se_code":"21","nm":"대학원 환경응용과학과","cd":"A02382","gb":"D","dh":"A01205"},
{"id":212,"enm":"Graduate School Department of Astronomy & Space Science","orgnz_outpt_ord":"890","orgnz_lvl_se_code":"21","nm":"대학원 우주과학과","cd":"A01710","gb":"D","dh":"A01205"},
{"id":213,"enm":"Graduate School Department of Food and Nutrition","orgnz_outpt_ord":"900","orgnz_lvl_se_code":"21","nm":"대학원 식품영양학과","cd":"A01622","gb":"D","dh":"A01205"},
{"id":214,"enm":"Graduate School Department of Clothing and Textile","orgnz_outpt_ord":"920","orgnz_lvl_se_code":"21","nm":"대학원 의상학과","cd":"A01846","gb":"D","dh":"A01205"},
{"id":215,"enm":"Graduate School Department of Landscape Architecture","orgnz_outpt_ord":"980","orgnz_lvl_se_code":"21","nm":"대학원 환경조경학과","cd":"A02361","gb":"D","dh":"A01205"},
{"id":216,"enm":"Graduate School Department of Biomedical Engineering","orgnz_outpt_ord":"1000","orgnz_lvl_se_code":"21","nm":"대학원 생체의공학과","cd":"A02573","gb":"D","dh":"A01205"},
{"id":217,"enm":"Graduate School Department of Nursing","orgnz_outpt_ord":"1010","orgnz_lvl_se_code":"21","nm":"대학원 간호학과","cd":"A01227","gb":"D","dh":"A01205"},
{"id":218,"enm":"Graduate School Department of Mechanical Engineering","orgnz_outpt_ord":"1040","orgnz_lvl_se_code":"21","nm":"대학원 기계공학과","cd":"A01332","gb":"D","dh":"A01205"},
{"id":219,"enm":"Graduate School Department of Chemical Engineering","orgnz_outpt_ord":"1060","orgnz_lvl_se_code":"21","nm":"대학원 화학공학과","cd":"A02257","gb":"D","dh":"A01205"},
{"id":220,"enm":"Graduate School Department of Electronic Engineering","orgnz_outpt_ord":"1080","orgnz_lvl_se_code":"21","nm":"대학원 전자공학과","cd":"A01910","gb":"D","dh":"A01205"},
{"id":221,"enm":"Graduate School Department of Nuclear Engineering","orgnz_outpt_ord":"1110","orgnz_lvl_se_code":"21","nm":"대학원 원자력공학과","cd":"A01737","gb":"D","dh":"A01205"},
{"id":222,"enm":"Graduate School Civil Engineering","orgnz_outpt_ord":"1130","orgnz_lvl_se_code":"21","nm":"대학원 사회기반시스템공학과","cd":"A02620","gb":"D","dh":"A01205"},
{"id":223,"enm":"Graduate School Department of Architectural Engineering","orgnz_outpt_ord":"1150","orgnz_lvl_se_code":"21","nm":"대학원 건축공학과","cd":"A01244","gb":"D","dh":"A01205"},
{"id":224,"enm":"Graduate School Industrial & Management Engineering","orgnz_outpt_ord":"1170","orgnz_lvl_se_code":"21","nm":"대학원 산업경영공학과","cd":"A02548","gb":"D","dh":"A01205"},
{"id":225,"enm":"Graduate School Department  of  formative  design","orgnz_outpt_ord":"1220","orgnz_lvl_se_code":"21","nm":"대학원 조형디자인학과","cd":"A02489","gb":"D","dh":"A01205"},
{"id":226,"enm":"Graduate School Department of Health Services Management","orgnz_outpt_ord":"1240","orgnz_lvl_se_code":"21","nm":"대학원 의료경영학과","cd":"A02493","gb":"D","dh":"A01205"},
{"id":227,"enm":"Graduate School Department of Fundamental Pharmaceutical Sciences","orgnz_outpt_ord":"1250","orgnz_lvl_se_code":"21","nm":"대학원 기초약학과","cd":"A02495","gb":"D","dh":"A01205"},
{"id":228,"enm":"Graduate School Department of Clinical Korean Medicine","orgnz_outpt_ord":"1270","orgnz_lvl_se_code":"21","nm":"대학원 임상한의학과","cd":"A02497","gb":"D","dh":"A01205"},
{"id":229,"enm":"Graduate School Department of Medical Science of Meridian","orgnz_outpt_ord":"1290","orgnz_lvl_se_code":"21","nm":"대학원 경락의과학과","cd":"A02519","gb":"D","dh":"A01205"},
{"id":230,"enm":"Graduate School Department of Cancer Preventive Material Development","orgnz_outpt_ord":"1300","orgnz_lvl_se_code":"21","nm":"대학원 암예방소재개발학과","cd":"A02523","gb":"D","dh":"A01205"},
{"id":231,"enm":"Graduate School Department of  Computer Science and Engineering","orgnz_outpt_ord":"1310","orgnz_lvl_se_code":"21","nm":"대학원 컴퓨터공학과","cd":"A02140","gb":"D","dh":"A01205"},
{"id":232,"enm":"Graduate School Department of Medicine","orgnz_outpt_ord":"1320","orgnz_lvl_se_code":"21","nm":"대학원 의학과","cd":"A01789","gb":"D","dh":"A01205"},
{"id":233,"enm":"Graduate School Department of Korean Medicine","orgnz_outpt_ord":"1330","orgnz_lvl_se_code":"21","nm":"대학원 한의학과","cd":"A02171","gb":"D","dh":"A01205"},
{"id":234,"enm":"Graduate School Department of Biomedical Science","orgnz_outpt_ord":"1340","orgnz_lvl_se_code":"21","nm":"대학원 기초의과학과","cd":"A02427","gb":"D","dh":"A01205"},
{"id":235,"enm":"Graduate School Department of Science in Korean Medicine","orgnz_outpt_ord":"1350","orgnz_lvl_se_code":"21","nm":"대학원 기초한의과학과","cd":"A02449","gb":"D","dh":"A01205"},
{"id":236,"enm":"Graduate School Department of Medical Engineering","orgnz_outpt_ord":"1360","orgnz_lvl_se_code":"21","nm":"대학원 생체의과학과","cd":"A02443","gb":"D","dh":"A01205"},
{"id":237,"enm":"Graduate School Department of Dentistry","orgnz_outpt_ord":"1370","orgnz_lvl_se_code":"21","nm":"대학원 치의학과","cd":"A02089","gb":"D","dh":"A01205"},
{"id":238,"enm":"Graduate School Department of Information Display","orgnz_outpt_ord":"1390","orgnz_lvl_se_code":"21","nm":"대학원 정보디스플레이학과","cd":"A02572","gb":"D","dh":"A01205"},
{"id":239,"enm":"Graduate School Department of East-West Medicine","orgnz_outpt_ord":"1400","orgnz_lvl_se_code":"21","nm":"대학원 동서의학과","cd":"A01400","gb":"D","dh":"A01205"},
{"id":240,"enm":"Graduate School Department of Physical Education","orgnz_outpt_ord":"1410","orgnz_lvl_se_code":"21","nm":"대학원 체육학과","cd":"A02051","gb":"D","dh":"A01205"},
{"id":241,"enm":"Graduate School Department of History in Korean Medicine","orgnz_outpt_ord":"1430","orgnz_lvl_se_code":"21","nm":"대학원 한의역사학","cd":"A02355","gb":"D","dh":"A01205"},
{"id":242,"enm":"Graduate School Department of Biological Sciences in Korean Medicine","orgnz_outpt_ord":"1440","orgnz_lvl_se_code":"21","nm":"대학원 한의생명과학","cd":"A02358","gb":"D","dh":"A01205"},
{"id":243,"enm":"Graduate School Department of Applied Korean Medicine","orgnz_outpt_ord":"1450","orgnz_lvl_se_code":"21","nm":"대학원 한방응용의학","cd":"A02372","gb":"D","dh":"A01205"},
{"id":244,"enm":"Graduate School Department of Dance","orgnz_outpt_ord":"1480","orgnz_lvl_se_code":"21","nm":"대학원 무용학과","cd":"A01416","gb":"D","dh":"A01205"},
{"id":245,"enm":"Graduate School Department of Music","orgnz_outpt_ord":"1490","orgnz_lvl_se_code":"21","nm":"대학원 음악학과","cd":"A01761","gb":"D","dh":"A01205"},
{"id":246,"enm":"Graduate School Department of Fine Arts","orgnz_outpt_ord":"1500","orgnz_lvl_se_code":"21","nm":"대학원 미술학과","cd":"A01448","gb":"D","dh":"A01205"},
{"id":247,"enm":"Graduate School Department of Industrial Design","orgnz_outpt_ord":"1520","orgnz_lvl_se_code":"21","nm":"대학원 산업디자인학과","cd":"A01527","gb":"D","dh":"A01205"},
{"id":248,"enm":"Graduate School Department of Education","orgnz_outpt_ord":"1550","orgnz_lvl_se_code":"21","nm":"대학원 교육학과","cd":"A02399","gb":"D","dh":"A01205"},
{"id":249,"enm":"Graduate School Department  of Architecture","orgnz_outpt_ord":"1610","orgnz_lvl_se_code":"21","nm":"대학원 건축학과","cd":"A02655","gb":"D","dh":"A01205"},
{"id":250,"enm":"Graduate School Ceramic Arts","orgnz_outpt_ord":"1660","orgnz_lvl_se_code":"21","nm":"대학원 도예학과","cd":"A02671","gb":"D","dh":"A01205"},
{"id":251,"enm":"Graduate School Department of Child & Family studies","orgnz_outpt_ord":"1820","orgnz_lvl_se_code":"21","nm":"대학원 아동가족학과","cd":"A02539","gb":"D","dh":"A01205"},
{"id":252,"enm":"Graduate School Department of Housing and Interior Design","orgnz_outpt_ord":"1830","orgnz_lvl_se_code":"21","nm":"대학원 주거환경학과","cd":"A02542","gb":"D","dh":"A01205"},
{"id":253,"enm":"Graduate School Department of Neuroscience","orgnz_outpt_ord":"1840","orgnz_lvl_se_code":"21","nm":"대학원 신경과학과","cd":"A02544","gb":"D","dh":"A01205"},
{"id":254,"enm":"Graduate School School of Space Research","orgnz_outpt_ord":"1850","orgnz_lvl_se_code":"21","nm":"대학원 우주탐사학과","cd":"A02546","gb":"D","dh":"A01205"},
{"id":255,"enm":"Graduate School Digital Art & Design","orgnz_outpt_ord":"1880","orgnz_lvl_se_code":"21","nm":"대학원 디지털콘텐츠학과","cd":"A02579","gb":"D","dh":"A01205"},
{"id":256,"enm":"Graduate School Department of film & theatre","orgnz_outpt_ord":"1890","orgnz_lvl_se_code":"21","nm":"대학원 연극영화학과","cd":"A02581","gb":"D","dh":"A01205"},
{"id":257,"enm":"Graduate School Department of Post Modern Music","orgnz_outpt_ord":"1900","orgnz_lvl_se_code":"21","nm":"대학원 포스트모던음악학과","cd":"A02583","gb":"D","dh":"A01205"},
{"id":258,"enm":"Graduate School Department of Applied Arts","orgnz_outpt_ord":"1910","orgnz_lvl_se_code":"21","nm":"대학원 응용예술학과","cd":"A02585","gb":"D","dh":"A01205"},
{"id":259,"enm":"Graduate School Advanced Material Engineering for Informations and Electronics","orgnz_outpt_ord":"1920","orgnz_lvl_se_code":"21","nm":"대학원 정보전자신소재공학과","cd":"A02587","gb":"D","dh":"A01205"},
{"id":260,"enm":"Graduate School Plant and Environmental New Resources","orgnz_outpt_ord":"1930","orgnz_lvl_se_code":"21","nm":"대학원 식물·환경신소재공학과","cd":"A02589","gb":"D","dh":"A01205"},
{"id":261,"enm":"Graduate School Department of Hotel Management","orgnz_outpt_ord":"1940","orgnz_lvl_se_code":"21","nm":"대학원 호텔경영학과","cd":"A02591","gb":"D","dh":"A01205"},
{"id":262,"enm":"Graduate School Department of Convention & Exhibition Management","orgnz_outpt_ord":"1970","orgnz_lvl_se_code":"21","nm":"대학원 컨벤션전시경영","cd":"A02602","gb":"D","dh":"A01205"},
{"id":263,"enm":"Graduate School Department of Horticultural Biotechnology","orgnz_outpt_ord":"1980","orgnz_lvl_se_code":"21","nm":"대학원 원예생명공학과","cd":"A02596","gb":"D","dh":"A01205"},
{"id":264,"enm":"Graduate School Department of Visual Information Design","orgnz_outpt_ord":"1990","orgnz_lvl_se_code":"21","nm":"대학원 시각정보디자인학과","cd":"A02598","gb":"D","dh":"A01205"},
{"id":265,"enm":"Graduate School Department of Textiles ＆ Fashion Design","orgnz_outpt_ord":"2000","orgnz_lvl_se_code":"21","nm":"대학원 텍스타일·패션디자인학과","cd":"A02600","gb":"D","dh":"A01205"},
{"id":266,"enm":"Graduate School Genetics & Biotechnology","orgnz_outpt_ord":"2040","orgnz_lvl_se_code":"21","nm":"대학원 유전생명공학과","cd":"A10274","gb":"D","dh":"A01205"},
{"id":267,"enm":"Graduate School Smart Tourism Education Platform","orgnz_outpt_ord":"2050","orgnz_lvl_se_code":"21","nm":"대학원 스마트관광원","cd":"A10347","gb":"D","dh":"A01205"},
{"id":268,"enm":"Graduate School Department of Smart City Planning and Real Estate","orgnz_outpt_ord":"2070","orgnz_lvl_se_code":"21","nm":"대학원 스마트도시·부동산학","cd":"A10349","gb":"D","dh":"A01205"},
{"id":269,"enm":"Graduate School The Department of Big Data Analytics","orgnz_outpt_ord":"2080","orgnz_lvl_se_code":"21","nm":"대학원 빅데이터응용학과","cd":"A10350","gb":"D","dh":"A01205"},
{"id":270,"enm":"Graduate School Department of Electronics and Information Convergence Engineering","orgnz_outpt_ord":"2100","orgnz_lvl_se_code":"21","nm":"대학원 전자정보융합공학과","cd":"A10408","gb":"D","dh":"A01205"},
{"id":271,"enm":"Graduate School Department of Biomedical and Pharmaceutical Sciences","orgnz_outpt_ord":"2110","orgnz_lvl_se_code":"21","nm":"대학원 융합생명의약학과","cd":"A10435","gb":"D","dh":"A01205"},
{"id":272,"enm":"Graduate School Department of Artificial Intelligence","orgnz_outpt_ord":"2120","orgnz_lvl_se_code":"21","nm":"대학원 인공지능학과","cd":"A10475","gb":"D","dh":"A01205"},
{"id":273,"enm":"Graduate School Department of regulatory science","orgnz_outpt_ord":"2140","orgnz_lvl_se_code":"21","nm":"대학원 규제과학","cd":"A10620","gb":"D","dh":"A01205"},
{"id":274,"enm":"Graduate School Department of media","orgnz_outpt_ord":"2150","orgnz_lvl_se_code":"21","nm":"대학원 미디어학","cd":"A10621","gb":"D","dh":"A01205"},
{"id":275,"enm":"Graduate School Department of Culture, Tourism & Content Culture ＆ Tourism Contents","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"대학원 문화관광콘텐츠학과 문화관광콘텐츠학과","cd":"A02635","gb":"D","dh":"A01205"},
{"id":276,"enm":"The Graduate School of Business Administration Off-campus","orgnz_outpt_ord":"100","orgnz_lvl_se_code":"21","nm":"경영대학원 Off-campus","cd":"A02941","gb":"D","dh":"A02745"},
{"id":277,"enm":"The Graduate School of Business Administration Department of Art & Cultural Management","orgnz_outpt_ord":"270","orgnz_lvl_se_code":"21","nm":"경영대학원 문화예술경영학과","cd":"A02846","gb":"D","dh":"A02745"},
{"id":278,"enm":"The Graduate School of Business Administration Department of Medical Management","orgnz_outpt_ord":"280","orgnz_lvl_se_code":"21","nm":"경영대학원 의료경영학과","cd":"A02880","gb":"D","dh":"A02745"},
{"id":279,"enm":"The Graduate School of Business Administration Department of Tax Management","orgnz_outpt_ord":"330","orgnz_lvl_se_code":"21","nm":"경영대학원 세무관리학과","cd":"A02871","gb":"D","dh":"A02745"},
{"id":280,"enm":"The Graduate School of Business Administration Department of Business Administration","orgnz_outpt_ord":"560","orgnz_lvl_se_code":"21","nm":"경영대학원 경영학과","cd":"A02752","gb":"D","dh":"A02745"},
{"id":281,"enm":"The Graduate School of Business Administration Department of Medical Management Major in Health Services Management","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"경영대학원 의료경영학과 의료경영학전공","cd":"A02881","gb":"D","dh":"A02745"},
{"id":282,"enm":"The Graduate School of Business Administration Department of Art & Cultural Management Performing Arts Management","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"경영대학원 문화예술경영학과 공연예술경영전공","cd":"A02847","gb":"D","dh":"A02745"},
{"id":283,"enm":"The Graduate School of Business Administration Department of Art & Cultural Management Major in Art & Cultural Policy","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"경영대학원 문화예술경영학과 문화예술정책전공","cd":"A02849","gb":"D","dh":"A02745"},
{"id":284,"enm":"The Graduate School of Business Administration Non-Degree Expert Program in Art & Cultural Management Major in Art & Cultural Policy","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"경영대학원 문화예술경영전문가과정 문화예술정책전공","cd":"A02903","gb":"D","dh":"A02745"},
{"id":285,"enm":"The Graduate School of Business Administration Department of Art & Cultural Management Major in Museum Management","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"30","nm":"경영대학원 문화예술경영학과 박물관미술관경영전공","cd":"A02851","gb":"D","dh":"A02745"},
{"id":286,"enm":"The Graduate School of Business Administration Department of Business Administration Major in Tax","orgnz_outpt_ord":"40","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 세무관리전공","cd":"A02773","gb":"D","dh":"A02745"},
{"id":287,"enm":"The Graduate School of Business Administration Department of Business Administration Major in Global","orgnz_outpt_ord":"50","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 국제경영전공","cd":"A02774","gb":"D","dh":"A02745"},
{"id":288,"enm":"The Graduate School of Business Administration Department of Business Administration Major in China Business","orgnz_outpt_ord":"70","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 중국경영전공","cd":"A02776","gb":"D","dh":"A02745"},
{"id":289,"enm":"The Graduate School of Business Administration Department of Business Administration Major in Brand Management","orgnz_outpt_ord":"80","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 브랜드매니지먼트전공","cd":"A02777","gb":"D","dh":"A02745"},
{"id":290,"enm":"The Graduate School of Business Administration Department of Business Administration Major in Management","orgnz_outpt_ord":"90","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 경영전공","cd":"A02778","gb":"D","dh":"A02745"},
{"id":291,"enm":"The Graduate School of Business Administration Department of Business Administration","orgnz_outpt_ord":"90","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과","cd":"A10690","gb":"D","dh":"A02745"},
{"id":292,"enm":"The Graduate School of Business Administration Department of Business Administration Major in Consulting","orgnz_outpt_ord":"120","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 경영컨설팅전공","cd":"A02782","gb":"D","dh":"A02745"},
{"id":293,"enm":"The Graduate School of Business Administration Department of Business Administration Start Up Business","orgnz_outpt_ord":"130","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 스타트업 비즈니스 전공","cd":"A02783","gb":"D","dh":"A02745"},
{"id":294,"enm":"The Graduate School of Business Administration Department of Business Administration AI Business","orgnz_outpt_ord":"330","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 AI비즈니스전공","cd":"A10426","gb":"D","dh":"A02745"},
{"id":295,"enm":"The Graduate School of Business Administration Department of Business Administration","orgnz_outpt_ord":"340","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 코칭사이언스전공","cd":"A10689","gb":"D","dh":"A02745"},
{"id":296,"enm":"The Graduate School of Business Administration Department of Business Administration","orgnz_outpt_ord":"350","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 서비스경영전공","cd":"A10684","gb":"D","dh":"A02745"},
{"id":297,"enm":"The Graduate School of Business Administration Department of Business Administration","orgnz_outpt_ord":"360","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 소셜미디어전공","cd":"A10685","gb":"D","dh":"A02745"},
{"id":298,"enm":"The Graduate School of Business Administration Department of Business Administration","orgnz_outpt_ord":"370","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 e커머스전공","cd":"A10686","gb":"D","dh":"A02745"},
{"id":299,"enm":"The Graduate School of Business Administration Department of Business Administration","orgnz_outpt_ord":"380","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 기술경영전공","cd":"A10687","gb":"D","dh":"A02745"},
{"id":300,"enm":"The Graduate School of Business Administration Department of Business Administration","orgnz_outpt_ord":"390","orgnz_lvl_se_code":"30","nm":"경영대학원 경영학과 6차산업융합경영전공","cd":"A10688","gb":"D","dh":"A02745"},
{"id":301,"enm":"Graduate Institute of Peace Studies Department of United Nations and the Art of Peace United Nations and the Art of Peace","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"평화복지대학원 유엔평화학과 유엔평화","cd":"A03437","gb":"D","dh":"A03375"},
{"id":302,"enm":"Graduate Institute of Peace Studies Department of International Peace and Governance Peace and Global Governance","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"평화복지대학원 국제평화-거버넌스학과 국제평화","cd":"A03439","gb":"D","dh":"A03375"},
{"id":303,"enm":"Graduate Institute of Peace Studies Department of International Peace and Governance Peace ＆ Security Policy","orgnz_outpt_ord":"40","orgnz_lvl_se_code":"30","nm":"평화복지대학원 국제평화-거버넌스학과 평화안보정책전공","cd":"A10154","gb":"D","dh":"A03375"},
{"id":304,"enm":"Graduate School of Tourism","orgnz_outpt_ord":"170","orgnz_lvl_se_code":"12","nm":"관광대학원","cd":"A03583","gb":"D","dh":"A03583"},
{"id":305,"enm":"Graduate School of Tourism Department of Wine and Sommelier","orgnz_outpt_ord":"50","orgnz_lvl_se_code":"21","nm":"관광대학원 와인·소믈리에학과","cd":"A03635","gb":"D","dh":"A03583"},
{"id":306,"enm":"Graduate School of Tourism Department of Real Estate","orgnz_outpt_ord":"70","orgnz_lvl_se_code":"21","nm":"관광대학원 부동산학과","cd":"A03641","gb":"D","dh":"A03583"},
{"id":307,"enm":"Graduate School of Tourism Department of Real Estate","orgnz_outpt_ord":"80","orgnz_lvl_se_code":"21","nm":"관광대학원 문화관광엔터테인먼트학과","cd":"A03652","gb":"D","dh":"A03583"},
{"id":308,"enm":"Graduate School of Tourism Department of Culinary Science & Foodservice Management","orgnz_outpt_ord":"210","orgnz_lvl_se_code":"21","nm":"관광대학원 조리외식경영학과","cd":"A03608","gb":"D","dh":"A03583"},
{"id":309,"enm":"Graduate School of Tourism Department of Tourism","orgnz_outpt_ord":"230","orgnz_lvl_se_code":"21","nm":"관광대학원 관광학과","cd":"A03610","gb":"D","dh":"A03583"},
{"id":310,"enm":"Graduate School of Tourism Department of Convention and Exhibition Management","orgnz_outpt_ord":"380","orgnz_lvl_se_code":"21","nm":"관광대학원 컨벤션전시경영학과","cd":"A03612","gb":"D","dh":"A03583"},
{"id":311,"enm":"School of Law Department of Law","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"21","nm":"법학전문대학원 법학과","cd":"A03688","gb":"D","dh":"A03687"},
{"id":312,"enm":"School of Law Department of Law Department of Law","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"법학전문대학원 법학과 법학","cd":"A03689","gb":"D","dh":"A03687"},
{"id":313,"enm":"Graduate School of Public Policy and Civic Engagement Department of Public Policy","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"21","nm":"공공대학원 정책학과","cd":"A03693","gb":"D","dh":"A03692"},
{"id":314,"enm":"Graduate School of Public Policy and Civic Engagement Department of Public Policy Public Policy","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공공대학원 정책학과 공공정책","cd":"A03694","gb":"D","dh":"A03692"},
{"id":315,"enm":"Graduate School of Public Policy and Civic Engagement Department of Health Service Hospital Administration","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공공대학원 의료관리학과 병원행정","cd":"A03699","gb":"D","dh":"A03692"},
{"id":316,"enm":"Graduate School of Public Policy and Civic Engagement Department of Social Welfare Older&Care Welfare","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공공대학원 사회복지학과 노인·케어복지","cd":"A03705","gb":"D","dh":"A03692"},
{"id":317,"enm":"Graduate School of Public Policy and Civic Engagement Department of Civil Society and  NGOs Civil Society and NGOs","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공공대학원 시민사회·NGO학과 시민사회 · NGO","cd":"A03709","gb":"D","dh":"A03692"},
{"id":318,"enm":"Graduate School of Public Policy and Civic Engagement Department of Global Governance Global Governance","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공공대학원 글로벌거버넌스학과 글로벌거버넌스","cd":"A03711","gb":"D","dh":"A03692"},
{"id":319,"enm":"Graduate School of Public Policy and Civic Engagement Department of Public Policy Major of Railway Safety Policy","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공공대학원 정책학과(계약학과) 철도안전정책전공","cd":"A03713","gb":"D","dh":"A03692"},
{"id":320,"enm":"Graduate School of Public Policy and Civic Engagement Department of Social Welfare Major of Social Sefety","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"공공대학원 사회복지학과(계약학과) 사회안전전공","cd":"A03716","gb":"D","dh":"A03692"},
{"id":321,"enm":"Graduate School of Public Policy and Civic Engagement Department of Social Welfare Social Welfare","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"공공대학원 사회복지학과 사회복지","cd":"A03702","gb":"D","dh":"A03692"},
{"id":322,"enm":"Graduate School of Public Policy and Civic Engagement Department of Public Policy Public Administration","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"공공대학원 정책학과(계약학과) 행정학전공","cd":"A03714","gb":"D","dh":"A03692"},
{"id":323,"enm":"Graduate School of Public Policy and Civic Engagement Department of Social Welfare Major in Early childhood ＆ Care","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"공공대학원 사회복지학과(계약학과) 유아.보육전공","cd":"A03717","gb":"D","dh":"A03692"},
{"id":324,"enm":"Graduate School of Public Policy and Civic Engagement Department of Health Service Nursing Administration","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"30","nm":"공공대학원 의료관리학과 간호행정","cd":"A03698","gb":"D","dh":"A03692"},
{"id":325,"enm":"Graduate School of Public Policy and Civic Engagement Department of Social Welfare Social Welfare","orgnz_outpt_ord":"5","orgnz_lvl_se_code":"40","nm":"공공대학원 사회복지학과 사회복지","cd":"A10185","gb":"D","dh":"A03692"},
{"id":326,"enm":"Graduate School of International Legal Affairs","orgnz_outpt_ord":"160","orgnz_lvl_se_code":"12","nm":"법무대학원","cd":"A03724","gb":"D","dh":"A03724"},
{"id":327,"enm":"Graduate School of East-West Medical Science East-west Medicine","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"21","nm":"동서의학대학원 동서의학과","cd":"A06528","gb":"D","dh":"A06502"},
{"id":328,"enm":"Graduate School of East-West Medical Science Medical Nutrition","orgnz_outpt_ord":"50","orgnz_lvl_se_code":"21","nm":"동서의학대학원 의학영양학과","cd":"A06538","gb":"D","dh":"A06502"},
{"id":329,"enm":"Graduate School of East-West Medical Science major in biogerontology","orgnz_outpt_ord":"170","orgnz_lvl_se_code":"21","nm":"동서의학대학원 노인학과 노화의과학전공","cd":"A06548","gb":"D","dh":"A06502"},
{"id":330,"enm":"Graduate School of East-West Medical Science major in gerontology","orgnz_outpt_ord":"190","orgnz_lvl_se_code":"21","nm":"동서의학대학원 노인학과 노년학전공","cd":"A06550","gb":"D","dh":"A06502"},
{"id":331,"enm":"Graduate School of East-West Medical Science Department of Comprehensive Health Science","orgnz_outpt_ord":"200","orgnz_lvl_se_code":"21","nm":"동서의학대학원 융합건강과학과","cd":"A06553","gb":"D","dh":"A06502"},
{"id":332,"enm":"Graduate School of East-West Medical Science Department of Gerontology AgeTech-Service Convergence Major (Major in Gerontology)","orgnz_outpt_ord":"210","orgnz_lvl_se_code":"21","nm":"동서의학대학원 노인학과 고령서비스-테크융합전공(노년학)","cd":"A10421","gb":"D","dh":"A06502"},
{"id":333,"enm":"Graduate School of East-West Medical Science Department of Gerontology AgeTech-Service Convergence Major (Major in Biogerontology)","orgnz_outpt_ord":"220","orgnz_lvl_se_code":"21","nm":"동서의학대학원 노인학과 고령서비스-테크융합전공(노화의과학)","cd":"A10422","gb":"D","dh":"A06502"},
{"id":334,"enm":"Graduate School of East-West Medical Science","orgnz_outpt_ord":"240","orgnz_lvl_se_code":"21","nm":"동서의학대학원 미래식품학과","cd":"A10593","gb":"D","dh":"A06502"},
{"id":335,"enm":"Graduate School of Pan-Pacific International Studies","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"12","nm":"국제대학원","cd":"A06573","gb":"D","dh":"A06573"},
{"id":336,"enm":"Graduate School of Pan-Pacific International Studies International Trade and Economic Cooperation International Trade and Economic Cooperation","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"국제대학원 국제통상협력학과 국제통상협력전공","cd":"A06579","gb":"D","dh":"A06573"},
{"id":337,"enm":"Graduate School of Pan-Pacific International Studies International Development and Cooperation International Development Cooperation","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"30","nm":"국제대학원 국제개발협력학과 국제개발협력학전공","cd":"A06599","gb":"D","dh":"A06573"},
{"id":338,"enm":"Graduate School of Pan-Pacific International Studies International Development and Cooperation International Development and Consulting","orgnz_outpt_ord":"40","orgnz_lvl_se_code":"30","nm":"국제대학원 국제개발협력학과 국제개발컨설팅전공","cd":"A06600","gb":"D","dh":"A06573"},
{"id":339,"enm":"Graduate School of Pan-Pacific International Studies International Business International Business","orgnz_outpt_ord":"60","orgnz_lvl_se_code":"30","nm":"국제대학원 국제경영학과 국제경영전공","cd":"A06576","gb":"D","dh":"A06573"},
{"id":340,"enm":"Graduate School of Pan-Pacific International Studies International Business Global Human Resource Management","orgnz_outpt_ord":"70","orgnz_lvl_se_code":"30","nm":"국제대학원 국제경영학과 국제인적자원경영전공","cd":"A10273","gb":"D","dh":"A06573"},
{"id":341,"enm":"Graduate School of Pan-Pacific International Studies International Business International Agro-Food Management and Entrepreneurship","orgnz_outpt_ord":"80","orgnz_lvl_se_code":"30","nm":"국제대학원 국제경영학과 국제농식품경영전공","cd":"A10272","gb":"D","dh":"A06573"},
{"id":342,"enm":"Graduate School of Pan-Pacific International Studies International Relations International Relations","orgnz_outpt_ord":"90","orgnz_lvl_se_code":"30","nm":"국제대학원 국제관계학과 국제관계학전공","cd":"A06586","gb":"D","dh":"A06573"},
{"id":343,"enm":"Graduate School of Physical Education Sports Medicine and Science","orgnz_outpt_ord":"120","orgnz_lvl_se_code":"21","nm":"체육대학원 스포츠의·과학전공","cd":"A06876","gb":"D","dh":"A06842"},
{"id":344,"enm":"Graduate School of Physical Education Sport Bigtainment","orgnz_outpt_ord":"280","orgnz_lvl_se_code":"21","nm":"체육대학원 스포츠빅테인먼트전공","cd":"A06891","gb":"D","dh":"A06842"},
{"id":345,"enm":"Graduate School of Physical Education Department of Taekwondo","orgnz_outpt_ord":"290","orgnz_lvl_se_code":"21","nm":"체육대학원 태권도학전공","cd":"A06893","gb":"D","dh":"A06842"},
{"id":346,"enm":"Graduate School of Art&Fusion Design Jazz & Contemporary Music Jazz & Contemporary Music","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"아트퓨전디자인대학원 실용음악학과 실용음악전공","cd":"A06942","gb":"D","dh":"A06895"},
{"id":347,"enm":"Graduate School of Technology Management","orgnz_outpt_ord":"140","orgnz_lvl_se_code":"12","nm":"테크노경영대학원","cd":"A06954","gb":"D","dh":"A06954"},
{"id":348,"enm":"Graduate School of Technology Management Department of Global Management","orgnz_outpt_ord":"70","orgnz_lvl_se_code":"21","nm":"테크노경영대학원 글로벌경영학과(3학기제)","cd":"A07025","gb":"D","dh":"A06954"},
{"id":349,"enm":"Graduate School of Technology Management Department of Global Management","orgnz_outpt_ord":"80","orgnz_lvl_se_code":"21","nm":"테크노경영대학원 글로벌경영학과(4학기제)","cd":"A07031","gb":"D","dh":"A06954"},
{"id":350,"enm":"Graduate School of Technology Management Department of Global Management","orgnz_outpt_ord":"100","orgnz_lvl_se_code":"21","nm":"테크노경영대학원 글로벌경영학과(4학기제-계약)","cd":"A07033","gb":"D","dh":"A06954"},
{"id":351,"enm":"Graduate School of Technology Management Department of Construction Safety and Health","orgnz_outpt_ord":"130","orgnz_lvl_se_code":"21","nm":"테크노경영대학원 건설안전보건학과","cd":"A07048","gb":"D","dh":"A06954"},
{"id":352,"enm":"Graduate School of Technology Management Department of Sports Management","orgnz_outpt_ord":"170","orgnz_lvl_se_code":"21","nm":"테크노경영대학원 스포츠경영학과(4학기제)","cd":"A07023","gb":"D","dh":"A06954"},
{"id":353,"enm":"Graduate School of Technology Management Department of Construction Safety Management","orgnz_outpt_ord":"260","orgnz_lvl_se_code":"21","nm":"테크노경영대학원 건설안전경영학과(4학기제공학)","cd":"A07019","gb":"D","dh":"A06954"},
{"id":354,"enm":"Graduate School of Technology Management Department of Welfare Management","orgnz_outpt_ord":"300","orgnz_lvl_se_code":"21","nm":"테크노경영대학원 복지경영학과(4학기제)","cd":"A10118","gb":"D","dh":"A06954"},
{"id":355,"enm":"Graduate School of Technology Management Department of Smart Technology Management","orgnz_outpt_ord":"360","orgnz_lvl_se_code":"21","nm":"테크노경영대학원 스마트기술경영학과(4학기제-계약)","cd":"A10320","gb":"D","dh":"A06954"},
{"id":356,"enm":"Graduate School of Technology Management Department of Future Innovation Management","orgnz_outpt_ord":"380","orgnz_lvl_se_code":"21","nm":"테크노경영대학원 미래혁신경영학과(4학기제-계약)","cd":"A10473","gb":"D","dh":"A06954"},
{"id":357,"enm":"Graduate School of Technology Management Department of  AI Technology Management","orgnz_outpt_ord":"390","orgnz_lvl_se_code":"21","nm":"테크노경영대학원 AI 기술경영학과 (4학기제-계약)","cd":"A10483","gb":"D","dh":"A06954"},
{"id":358,"enm":"Graduate School of Education","orgnz_outpt_ord":"110","orgnz_lvl_se_code":"12","nm":"교육대학원","cd":"A10083","gb":"D","dh":"A10083"},
{"id":359,"enm":"Graduate School of Education Innovative Education","orgnz_outpt_ord":"90","orgnz_lvl_se_code":"21","nm":"교육대학원 혁신교육전공","cd":"A10111","gb":"D","dh":"A10083"},
{"id":360,"enm":"Graduate School of Education Lifelong Education","orgnz_outpt_ord":"110","orgnz_lvl_se_code":"21","nm":"교육대학원 평생교육전공","cd":"A03190","gb":"D","dh":"A10083"},
{"id":361,"enm":"Graduate School of Education Major in Korean Language as a Second Language Education","orgnz_outpt_ord":"170","orgnz_lvl_se_code":"21","nm":"교육대학원 외국어로서의한국어교육전공","cd":"A03039","gb":"D","dh":"A10083"},
{"id":362,"enm":"Graduate School of Education","orgnz_outpt_ord":"320","orgnz_lvl_se_code":"21","nm":"교육대학원 교직전공","cd":"A02990","gb":"D","dh":"A10083"},
{"id":363,"enm":"Graduate School of Education Department of Korean Education","orgnz_outpt_ord":"460","orgnz_lvl_se_code":"21","nm":"교육대학원 국어교육전공","cd":"A02993","gb":"D","dh":"A10083"},
{"id":364,"enm":"Graduate School of Education Department of English Education","orgnz_outpt_ord":"470","orgnz_lvl_se_code":"21","nm":"교육대학원 영어교육전공","cd":"A03035","gb":"D","dh":"A10083"},
{"id":365,"enm":"Graduate School of Education Department of Chinese Education","orgnz_outpt_ord":"570","orgnz_lvl_se_code":"21","nm":"교육대학원 중국어교육전공","cd":"A03063","gb":"D","dh":"A10083"},
{"id":366,"enm":"Graduate School of Education Department of Mathematics Education","orgnz_outpt_ord":"600","orgnz_lvl_se_code":"21","nm":"교육대학원 수학교육전공","cd":"A03027","gb":"D","dh":"A10083"},
{"id":367,"enm":"Graduate School of Education Department of Physics Education","orgnz_outpt_ord":"610","orgnz_lvl_se_code":"21","nm":"교육대학원 물리교육전공","cd":"A03006","gb":"D","dh":"A10083"},
{"id":368,"enm":"Graduate School of Education Department of Chemistry Education","orgnz_outpt_ord":"630","orgnz_lvl_se_code":"21","nm":"교육대학원 화학교육전공","cd":"A03088","gb":"D","dh":"A10083"},
{"id":369,"enm":"Graduate School of Education Department of Biology Education","orgnz_outpt_ord":"640","orgnz_lvl_se_code":"21","nm":"교육대학원 생물교육전공","cd":"A03023","gb":"D","dh":"A10083"},
{"id":370,"enm":"Graduate School of Education Major in Museun & Art Gallery Education","orgnz_outpt_ord":"700","orgnz_lvl_se_code":"21","nm":"교육대학원 박물관.미술관교육전공","cd":"A03095","gb":"D","dh":"A10083"},
{"id":371,"enm":"Graduate School of Education Department of Business Education","orgnz_outpt_ord":"750","orgnz_lvl_se_code":"21","nm":"교육대학원 상업교육전공","cd":"A03021","gb":"D","dh":"A10083"},
{"id":372,"enm":"Graduate School of Education Educational Psychology","orgnz_outpt_ord":"780","orgnz_lvl_se_code":"21","nm":"교육대학원 교육심리전공","cd":"A02986","gb":"D","dh":"A10083"},
{"id":373,"enm":"Graduate School of Education Health Education","orgnz_outpt_ord":"810","orgnz_lvl_se_code":"21","nm":"교육대학원 보건교육전공","cd":"A02980","gb":"D","dh":"A10083"},
{"id":374,"enm":"Graduate School of Education Department of Music Education","orgnz_outpt_ord":"820","orgnz_lvl_se_code":"21","nm":"교육대학원 음악교육전공","cd":"A03049","gb":"D","dh":"A10083"},
{"id":375,"enm":"Graduate School of Education Department of Fine Arts Education","orgnz_outpt_ord":"830","orgnz_lvl_se_code":"21","nm":"교육대학원 미술교육전공","cd":"A03008","gb":"D","dh":"A10083"},
{"id":376,"enm":"Graduate School of Education Department of Design Education","orgnz_outpt_ord":"850","orgnz_lvl_se_code":"21","nm":"교육대학원 디자인교육전공","cd":"A03004","gb":"D","dh":"A10083"},
{"id":377,"enm":"Graduate School of Education Department of Physical Education","orgnz_outpt_ord":"860","orgnz_lvl_se_code":"21","nm":"교육대학원 체육교육전공","cd":"A03073","gb":"D","dh":"A10083"},
{"id":378,"enm":"Graduate School of Education Graduate School of Education","orgnz_outpt_ord":"880","orgnz_lvl_se_code":"21","nm":"교육대학원 상담심리전공","cd":"A03019","gb":"D","dh":"A10083"},
{"id":379,"enm":"Graduate School of Education Preschool Education","orgnz_outpt_ord":"890","orgnz_lvl_se_code":"21","nm":"교육대학원 유아교육전공","cd":"A03044","gb":"D","dh":"A10083"},
{"id":380,"enm":"Graduate School of Education Department of General Social Education","orgnz_outpt_ord":"920","orgnz_lvl_se_code":"21","nm":"교육대학원 일반사회교육전공","cd":"A03054","gb":"D","dh":"A10083"},
{"id":381,"enm":"Graduate School of Education Department of History Education","orgnz_outpt_ord":"1030","orgnz_lvl_se_code":"21","nm":"교육대학원 역사교육전공","cd":"A03033","gb":"D","dh":"A10083"},
{"id":382,"enm":"Graduate School of Education Major in nutrition Education","orgnz_outpt_ord":"1040","orgnz_lvl_se_code":"21","nm":"교육대학원 영양교육전공","cd":"A03158","gb":"D","dh":"A10083"},
{"id":383,"enm":"Graduate School of Education Major in Educational Methods and Educational Technology","orgnz_outpt_ord":"1170","orgnz_lvl_se_code":"21","nm":"교육대학원 교육방법및교육공학전공","cd":"A03198","gb":"D","dh":"A10083"},
{"id":384,"enm":"Graduate School of Education 교육정책 및 리더십 전공","orgnz_outpt_ord":"1210","orgnz_lvl_se_code":"21","nm":"교육대학원 교육정책및리더십전공","cd":"A10123","gb":"D","dh":"A10083"},
{"id":385,"enm":"Graduate School of Education Major in Teacher Leadership Major in Teacher Leadership","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"교육대학원 교사리더십 교사리더십","cd":"A03201","gb":"D","dh":"A10083"},
{"id":386,"enm":"Graduate School of Education  Additional Theories in Teacher Education & Teaching(ATET)","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"교육대학원 교직전공 교직기타","cd":"A10246","gb":"D","dh":"A10083"},
{"id":387,"enm":"Graduate School of Media & Communication Department of Cultural contents","orgnz_outpt_ord":"170","orgnz_lvl_se_code":"21","nm":"미디어커뮤니케이션대학원 문화콘텐츠학과","cd":"A10489","gb":"D","dh":"A10486"},
{"id":388,"enm":"Graduate School of Media & Communication Department of Strategic Communication","orgnz_outpt_ord":"200","orgnz_lvl_se_code":"21","nm":"미디어커뮤니케이션대학원 전략커뮤니케이션학과","cd":"A10490","gb":"D","dh":"A10486"},
{"id":389,"enm":"Graduate School of Media & Communication Department of Journalism","orgnz_outpt_ord":"230","orgnz_lvl_se_code":"21","nm":"미디어커뮤니케이션대학원 저널리즘학과","cd":"A10493","gb":"D","dh":"A10486"},
{"id":390,"enm":"Graduate School of Nursing Department of Nursing Certificate Program of Gerontology Nurse Practitioner","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"간호대학원 간호학과 노인전문간호사전공","cd":"A10601","gb":"D","dh":"A10587"},
{"id":391,"enm":"Graduate School of Nursing Department of Nursing Certificate Program of Psychiatric Mental Health Nurse Practitioner","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"간호대학원 간호학과 정신전문간호사전공","cd":"A10602","gb":"D","dh":"A10587"},
{"id":392,"enm":"Graduate School of Nursing Department of Nursing Clinical Nurse Specialist","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"30","nm":"간호대학원 간호학과 임상간호전문가전공","cd":"A10603","gb":"D","dh":"A10587"}
]
}


daehak_202220 = {"rows":[
{"id":1,"enm":"College of Sciences","or_seq":"50","up":"A10081","nm":"이과대학","cd":"A01043","gb":"H"},
{"id":2,"enm":"College of Music","or_seq":"100","up":"A10081","nm":"음악대학","cd":"A00645","gb":"H"},
{"id":3,"enm":"College of Fine Arts","or_seq":"110","up":"A10081","nm":"미술대학","cd":"A01085","gb":"H"},
{"id":4,"enm":"Convergence","or_seq":"605","up":"A10081","nm":"융합(서울)","cd":"A10671","gb":"H"}
]
}

major_202220 = {"rows":[
{"id":1,"enm":"College of Music","orgnz_outpt_ord":"100","orgnz_lvl_se_code":"11","nm":"음악대학","cd":"A00645","gb":"H","dh":"A00645"},
{"id":2,"enm":"College of Music Department of Orchestral Instruments and Piano Musical Instrument","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"음악대학 기악과 기악","cd":"A00651","gb":"H","dh":"A00645"},
{"id":3,"enm":"College of Music Department of Voice Vocal Music","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"음악대학 성악과 성악","cd":"A00654","gb":"H","dh":"A00645"},
{"id":4,"enm":"College of Music Department of Composition Composition","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"음악대학 작곡과 작곡","cd":"A00658","gb":"H","dh":"A00645"},
{"id":5,"enm":"College of Sciences Department of Geography Geography","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"이과대학 지리학과 지리학","cd":"A01050","gb":"H","dh":"A01043"},
{"id":6,"enm":"College of Sciences Department of Information Display Information Display","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"이과대학 정보디스플레이학과 정보디스플레이학","cd":"A01059","gb":"H","dh":"A01043"},
{"id":7,"enm":"College of Sciences Department of Mathematics Mathematics","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"이과대학 수학과 수학","cd":"A01063","gb":"H","dh":"A01043"},
{"id":8,"enm":"College of Sciences Department of Physics Physics","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"이과대학 물리학과 물리학","cd":"A01065","gb":"H","dh":"A01043"},
{"id":9,"enm":"College of Sciences Department of Chemistry Chemistry","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"이과대학 화학과 화학","cd":"A01068","gb":"H","dh":"A01043"},
{"id":10,"enm":"College of Sciences Department of Biology Biology","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"이과대학 생물학과 생물학","cd":"A01070","gb":"H","dh":"A01043"},
{"id":11,"enm":"College of Fine Arts School of Fine Art","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"20","nm":"미술대학 미술학부","cd":"A01086","gb":"H","dh":"A01085"},
{"id":12,"enm":"College of Fine Arts School of Fine Art Korean Painting","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"미술대학 미술학부 한국화","cd":"A01087","gb":"H","dh":"A01085"},
{"id":13,"enm":"College of Fine Arts School of Fine Art Painting","orgnz_outpt_ord":"20","orgnz_lvl_se_code":"30","nm":"미술대학 미술학부 회화","cd":"A01088","gb":"H","dh":"A01085"},
{"id":14,"enm":"College of Fine Arts School of Fine Art Sculpture","orgnz_outpt_ord":"30","orgnz_lvl_se_code":"30","nm":"미술대학 미술학부 조소","cd":"A01089","gb":"H","dh":"A01085"},
{"id":15,"enm":"Convergence Science Information Convergence Major Science Information Convergence Major","orgnz_outpt_ord":"10","orgnz_lvl_se_code":"30","nm":"융합(서울) 과학지능정보 과학지능정보융합전공","cd":"A10678","gb":"H","dh":"A10671"}
]
}


daehak_202215 = {"rows":[
]
}

major_202215 = {"rows":[
]
}


daehak_202225 = {"rows":[
]
}

major_202225 = {"rows":[
]
}


gradIsuCd_2022 = {"rows":[
{"id":1,"nmk":"구분없음","cd":"00","nme":"No Section"},
{"id":2,"nmk":"전공필수","cd":"04","nme":"Essential Major Studies"},
{"id":3,"nmk":"전공선택","cd":"05","nme":"Elective Major Studies"},
{"id":4,"nmk":"교직","cd":"06","nme":"Teaching Profession"},
{"id":5,"nmk":"자유선택","cd":"08","nme":"Elective"},
{"id":6,"nmk":"공통과목","cd":"10","nme":"Common Subject"},
{"id":7,"nmk":"전공기초","cd":"11","nme":"Basic Major Studies"},
{"id":8,"nmk":"전공공통","cd":"12","nme":"Major (Common Subject)"},
{"id":9,"nmk":"공통필수","cd":"13","nme":"Common Essential"},
{"id":10,"nmk":"교직전선","cd":"20","nme":"Teaching Profession"},
{"id":11,"nmk":"선수과목","cd":"41","nme":"Pre-requisite Courses"},
{"id":12,"nmk":"논문지도과목","cd":"43","nme":"Thesis Subject"},
{"id":13,"nmk":"종합시험","cd":"44","nme":"Comprehensive Exam"},
{"id":14,"nmk":"외국어대체","cd":"61","nme":"Foreign Language (Substitute)"},
{"id":15,"nmk":"논문대체","cd":"66","nme":"Thesis Substitute"},
{"id":16,"nmk":"과정구분없음","cd":"95","nme":"No Category for Courses"}
]
}
