# Generated by Django 3.0.5 on 2020-10-22 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='createdAt',
            new_name='create_at',
        ),
    ]
