# Generated by Django 3.0.5 on 2020-10-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('article', '0002_auto_20201022_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='board.Board'),
        ),
    ]
