# Generated by Django 3.0.5 on 2020-10-22 15:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='images',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
