# Generated by Django 3.0.5 on 2020-10-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201023_0155'),
        ('article', '0006_auto_20201023_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.KhumuUser'),
        ),
    ]
