# sqlite3를 사용하고 싶을 때
database:
  engine: django.db.backends.sqlite3
  name: ./db.sqlite3
  user:
  password:
  host:
  port:
sns:
  enabled: true
  topicArn: arn:aws:sns:ap-northeast-2:xxxxx:xxxxx
cache:
  enabled: true
  endpoint: redis://127.0.0.1:6379/0
slack:
  botToken: ""
