# Generated by Django 3.0.5 on 2020-10-22 16:55

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('board', '0001_initial'),
        ('comment', '0001_initial'),
        ('article', '0005_auto_20201023_0015'),
        ('auth', '0011_update_proxy_permissions'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhumuUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(default='khumu', max_length=16)),
                ('nickname', models.CharField(default='흡혈형사', max_length=10)),
                ('student_number', models.CharField(default='2000123123', max_length=10)),
                ('memo', models.TextField(default='안녕, 잘 부탁해', max_length=150)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='KHUUser',
        ),
    ]
