# Generated by Django 3.0.5 on 2020-10-22 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201023_0155'),
        ('board', '0003_auto_20201023_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='long_name',
            field=models.CharField(default='국제캠퍼스', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='short_name',
            field=models.CharField(default='국제캠', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.KhumuUser'),
        ),
    ]
